### ISSUE TITLE
Crashes on Lollipop

### ISSUE THREAD

**Issue by vangorra** [chrisjenx/Calligraphy#113]
I use a lot of custom views in my app. Using Calligraphy on a Kitkat emulator works perfectly. Running the same app on a Lollipop emulator crashes on startup with an exception. I've followed the instructions in the README and run this.getActivity().getLayoutInflater.inflate when using onCreateView in fragments. It doesn't make a difference.

This occurs on version 1.1.0 and 1.2.0.

```
01-13 20:30:15.473    1806-1806/com.ccc.project.debug.main E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.ccc.project.debug.main, PID: 1806
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ccc.project.debug.main/com.ccc.lib.project.activity.MainActivity}: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.ccc.lib.fragment.LayoutFragment.onCreateView(LayoutFragment.java:55)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at com.ccc.lib.activity.IBusActivity.onStart(IBusActivity.java:80)
            at com.ccc.lib.project.activity.MainActivity.onStart(MainActivity.java:215)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.ccc.lib.fragment.LayoutFragment.onCreateView(LayoutFragment.java:55)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at com.ccc.lib.activity.IBusActivity.onStart(IBusActivity.java:80)
            at com.ccc.lib.project.activity.MainActivity.onStart(MainActivity.java:215)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.RuntimeException: Cannot make calls to a recycled instance!
            at android.content.res.TypedArray.getResourceId(TypedArray.java:694)
            at com.ccc.lib.widget.CByteArrayAggregator.applyAttributes(CByteArrayAggregator.java:101)
            at com.ccc.lib.widget.CByteArrayAggregator.<init>(CByteArrayAggregator.java:65)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at com.ccc.lib.fragment.LayoutFragment.onCreateView(LayoutFragment.java:55)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at com.ccc.lib.activity.IBusActivity.onStart(IBusActivity.java:80)
            at com.ccc.lib.project.activity.MainActivity.onStart(MainActivity.java:215)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
            at android.app.Activity.performStart(Activity.java:5949)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by chrisjenx** [comment]
There is no mention of Calligraphy in the stack trace, there are known issues with <1.2.1. But not crashes.
If removing Calligraphy fixes the crash great, but this looks unrelated. There is also a 2.0.0 snapshot designed for Lollipop.

**Comment by vangorra** [comment]
The maven repository doesn't have a 1.2.1 nor 2.0.0 snapshot. Further, there are not any branches or tags for the aforementioned versions. I'm happy to try them out, I just need them.

Finally, just because Calligraphy was not mentioned in this stack trace does not make it part of the issue. When loading fragments, Android runs the transaction on its own managed thread. So when you tell a fragment to show, the code that is responsible for the crash often isn't represented. One of many frustrations pointed out by Square Soft http://corner.squareup.com/2014/10/advocating-against-android-fragments.html.

Because the app only fails on Android 5.0 with Calligraphy enabled, I think there is enough of an issue to merit further investigation. Since the OP did not raise any immediate flags, I will delve a bit deeper and see if I can find a cause.

**Comment by vangorra** [comment]
The issue was indeed with my code. I have Calligraphy 1.2.0 working great with Android 5.0. Would still like to get information on how to get Calligraphy 2.0.0 though.

**Comment by chrisjenx** [comment]
See #105 for info how to try 2.0.0 snapshot. Thanks! Unfortunatly due to the way View are inflated it is often confusing where the issue lies. Generally if one customview works and another doesn't is almost certainly not going to be Calligraphy. Just remember use the double param constructor as that is the default for custom views.
