### ISSUE TITLE
Font path not passed correctly

### ISSUE THREAD

**Issue by geft** [chrisjenx/Calligraphy#114]
For some reason I couldn't get styles to work correctly. The custom font loads fine when I type it directly in XML or set it as the default font in OnCreate(). However, when I use styles, they just refuse to load. This is the 2.0.0 snapshot build.

Here is my style xml

```
<resources>

    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar"/>

    <style name="Font">
        <item name="android:textColor">@color/brown</item>
        <item name="android:textSize">18sp</item>
    </style>

    <style name="Font.Bold">
        <item name="fontPath">fonts/belwe_bt.otf</item>
    </style>

    <style name="Font.Hollow">
        <item name="fontPath">fonts/belwe_hollow.ttf</item>
    </style>

    <style name="Font.Regular">
        <item name="fontPath">fonts/archivo.ttf</item>
    </style>

    <style name="Font.Italics">
        <item name="fontPath">fonts/archivo_i.ttf</item>
    </style>

</resources>
```

The color and sizing work correctly, but the font fails at `createFromAsset()`. The paths are correct, because when I set them in XML, they work correctly.

Below is the error message. Notice that the asset path shown is not your typical text. Try selecting it for example. Multiple runs have gotten me Arabic, Russian and Mongolian strings, so I guess some random unicode text is what's being passed for some reason.

    W/Calligraphy﹕ Can't create asset from ‏‮NEW:‬‏ ‏‮‬‏. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: Font asset not found ‏‮NEW:‬‏ ‏‮‬‏
            at android.graphics.Typeface.createFromAsset(Typeface.java:190)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:141)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:173)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:131)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)

**Comment by chrisjenx** [comment]
Oh thats interesting. Haven't seen that before? Was this happening pre 2.0.0?

**Comment by geft** [comment]
I have no idea. I just started using it, looked at past isses to get the snapshot working and here I am.

**Comment by geft** [comment]
Oh, this is on Lollipop by the way. Like I said, it works correctly on anything but styles.

**Comment by chrisjenx** [comment]
@geft can you give me any more build info? Gradle/Target SDK? etc...

**Comment by geft** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.lifeof843.hearthstonereference"
        minSdkVersion 17
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-v4:21.0.3'
    compile 'uk.co.chrisjenx:calligraphy:2.0.0-SNAPSHOT'
}
```

**Comment by chrisjenx** [comment]
Awesome thanks!

**Comment by geft** [comment]
No problem, hope you can get it sorted. For now I'll just key them manually.

**Comment by chrisjenx** [comment]
Ok cool

**Comment by geft** [comment]
I think I just pinpointed where the error is from. Any idea what's causing this?

http://i.imgur.com/dsU6gzF.png

**Comment by geft** [comment]
It's [line 149](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java#L149)

Calling [lline 155](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyUtils.java#L155)

Getting warmer...

**Comment by geft** [comment]
I have no idea how the string is parsed...

**Comment by chrisjenx** [comment]
The string is pulled from the framework as you can see it just uses the R.id.fontPath Attr and pulls it from the style. Looks like a very odd framework issue. Wonder if there is a bug raised for it on Lollipop

**Comment by chrisjenx** [comment]
I suspect [this line L189](https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyUtils.java#L189) although I can't replicate the issue so I cannot verify if its fixed :/

**Comment by chrisjenx** [comment]
@geft how do define the style to the TextView?

**Comment by chrisjenx** [comment]
Also which device?

**Comment by geft** [comment]
```
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/itemText"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="0.925"
        android:gravity="center_vertical"
        android:minHeight="?android:attr/listPreferredItemHeightSmall"
        android:textAppearance="?android:attr/textAppearanceListItemSmall"
        fontPath="fonts/belwe.otf"
        tools:ignore="MissingPrefix" />
```

Nexus 5 5.0.2

**Comment by geft** [comment]
That works correctly, but it doesn't work when using android:theme for styles.xml

**Comment by chrisjenx** [comment]
@geft are you able to extract out to the simplest project? Or see if you can break the Calligraphy sample app? As I can't replicate the issue :(

**Comment by geft** [comment]
I just recreated it through a simple project, which can be downloaded [here](https://www.dropbox.com/s/ey774qyrvomokd2/Test.zip?dl=0).

```
01-16 12:48:52.617    9994-9994/com.lifeof843.test W/Calligraphy﹕ Can't create asset from Acest lucru va genera costuri în contul dvs. mobil.. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: Font asset not found Acest lucru va genera costuri în contul dvs. mobil.
            at android.graphics.Typeface.createFromAsset(Typeface.java:190)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:141)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:173)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:131)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.lifeof843.test.MainActivity.onCreate(MainActivity.java:17)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
01-16 12:48:52.641   9994-10012/com.lifeof843.test D/OpenGLRenderer﹕ Render dirty regions requested: true
01-16 12:48:52.651    9994-9994/com.lifeof843.test D/Atlas﹕ Validating map...
01-16 12:48:52.686   9994-10012/com.lifeof843.test I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: QUALCOMM Build: 10/24/14, 167c270, I68fa98814b
01-16 12:48:52.686   9994-10012/com.lifeof843.test I/OpenGLRenderer﹕ Initialized EGL, version 1.4
01-16 12:48:52.700   9994-10012/com.lifeof843.test D/OpenGLRenderer﹕ Enabling debug mode 0
```

**Comment by chrisjenx** [comment]
Right I see, why are you using `android:theme=...` instead of `style=..`? 
Not even sure where to start with `android:theme`.... Never used it. 

Suffice to say use `style="@style/StyleName"` problem solved!

**Comment by geft** [comment]
Ah, I see! I couldn't find `android:style` so I used theme instead. Turns out it doesn't use a namespace either. Oh well, feel free to close this. Thanks for the help.

**Comment by chrisjenx** [comment]
Haha no worries! It's all a learning experience, I'm not quite sure why
there is no namespace on `style` never mind. Thanks! :)

**Comment by bendaniel10** [comment]
I had this issue too. I found out that I put my assets folder in res. The correct way is to put the assets folder in the main folder instead. 

Correct: .../main/assets/fonts
Wrong: .../main/res/assets/fonts

**Comment by DevendraSingh91** [comment]
Did you guys sorted it out?
@chrisjenx @bendaniel10

**Comment by chrisjenx** [comment]
If there is another issue please raise a new one. Thanks.
