### ISSUE TITLE
Using Custom Font Error

### ISSUE THREAD

**Issue by ayz4sci** [chrisjenx/Calligraphy#119]
Hi,

Thank you for this library.

I'm get the error below. I've checked the following:
Your font is in the assets folder.
Your path is correct. assets/fonts/Typeface.ttf would equal fonts/Typeface.tff in Calligraphy.
Your your extension is correct, you can't omit the file extension, (leave ttf/otf) on the end.
Check case, Android is a case sensitive file system.

But still getting the error. Btw, I'm using Material Design.

com.deliveryscience.ughelistock W/Calligraphy﹕ Can't create asset from fonts/avenir-light.ttf. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: native typeface cannot be made
            at android.graphics.Typeface.<init>(Typeface.java:307)
            at android.graphics.Typeface.createFromAsset(Typeface.java:281)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:123)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:144)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:173)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:131)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.deliveryscience.ughelistock.SplashLogin.onCreate(SplashLogin.java:67)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

**Comment by chrisjenx** [comment]
Someone else reported this. It appeared that the .ttf was corrupt or not compatible with Android (does happen sometimes.)

If the the error is reporting the file path correctly is generally out of Calligraphies reach as we wrap the `Typeface.createFromAsset()`.

Just double check your .ttf (I still do it as .tff sometimes).
Try another opentype font (Roboto etc, they always work).

**Comment by ayz4sci** [comment]
Hi,

I tried using another extension .otf but still got the same error.

**Comment by chrisjenx** [comment]
Does roboto not work?

**Comment by ayz4sci** [comment]
Yes I did but still got the same error.

**Comment by chrisjenx** [comment]
What build system are you using. I wonder if your assets are being
compressed or something similar.

**Comment by ayz4sci** [comment]
Here is my gradle build code

apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.0"

    defaultConfig {
        applicationId "com.xxx.xx"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("Keystore.ks")
            storePassword "xxxxx"
            keyAlias "xx"
            keyPassword "xxxx"
        }
        debug {
            storeFile file("Keystore.ks")
            storePassword "xxxx"
            keyAlias "xx"
            keyPassword "xxxx"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
            signingConfig signingConfigs.release
        }
        debug {
            zipAlignEnabled true
        }
    }
}

repositories {
    maven { url 'http://raw.github.com/wada811/Android-Material-Design-Colors/master/repository/' }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile fileTree(dir: 'libs', include: 'Parse-*.jar')
    compile 'at.wada811:android-material-design-colors:1.2.0'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile files('libs/Parse-1.8.0.jar')
    compile files('libs/bolts-android-1.1.4.jar')
    compile project(':library')
    compile files('libs/simpleprovider-1.1.0.jar')
    compile project(':FloatingActionButtons')
    compile files('libs/volley.jar')
    compile 'uk.co.chrisjenx:calligraphy:2.0.0'
}

**Comment by chrisjenx** [comment]
Can you upgrade to `buildToolsVersion "21.1.2"` and report back.

This is very odd. I'm not convinced this is a Calligraphy issue tbh.

Also try to manually load the font yourself using
`Typeface.createFromAsset(getAsset(),"fonts/fontname.ttf")`

**Comment by ayz4sci** [comment]
I've been able to sort it. I was putting my asset folder inside res folder instead of src/main.
Thanks for your prompt response.

**Comment by chrisjenx** [comment]
Ahhh @ayz4sci no worries! Glad you resolved it! :+1:
