### ISSUE TITLE
Can't create asset from res/drawable-xhdpi-v4/btn_minus_disable.png.

### ISSUE THREAD

**Issue by finneapps** [chrisjenx/Calligraphy#125]
I am getting this error/warning: Can't create asset from res/drawable-xhdpi-v4/btn_minus_disable.png.
I dont know where the btn_minus_disable.png is comming from

W/Calligraphy﹕ Can't create asset from res/drawable-xhdpi-v4/btn_minus_disable.png. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: Font asset not found res/drawable-xhdpi-v4/btn_minus_disable.png
            at android.graphics.Typeface.createFromAsset(Typeface.java:190)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:141)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:175)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:133)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:296)
            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.support.v7.internal.view.menu.BaseMenuPresenter.createItemView(BaseMenuPresenter.java:161)
            at android.support.v7.internal.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:180)
            at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:170)
            at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:429)
            at android.support.v7.internal.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1129)
            at android.support.v7.internal.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:91)
            at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:207)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:279)
            at android.support.v7.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1021)
            at android.support.v7.internal.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1044)
            at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:465)
            at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by chrisjenx** [comment]
I have seen this a few times. I would check you are using `style="..."` to apply styles. Also check you are using the latest sdk/build tools. And that you are using `R.attr.fontPath` (or your own attr applied correctly). This generally comes from styles being merged/applied incorrectly.

**Comment by finneapps** [comment]
ok, thanks for your reply. I have not found a solution for this yet

**Comment by chrisjenx** [comment]
Are you using multi dex?

**Comment by finneapps** [comment]
No I am not using multi dex

**Comment by chrisjenx** [comment]
Can you add give code examples of how its integrated/applied to your project? I might be able to spot a style inheritance issue.

**Comment by finneapps** [comment]
I think it is because I try to change the font in my toolbar. I apply MyToolbarStyle to my toolbar and the theme is set to MyToolbarStyleText where I define <item name="fontPath">fonts/proxima-nova-bold.otf</item>

<style name="MyToolbarStyle" parent="Widget.AppCompat.Toolbar">
        <item name="popupTheme">@style/Dark.Overlay.LightPopup</item>
        <item name="theme">@style/MyToolbarStyleText</item>
        
        
        <item name="windowActionBarOverlay">true</item>
        <item name="android:statusBarColor">@color/colorPrimaryDark</item>
        

    </style>


    <style name="MyToolbarStyleText" parent="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
        <item name="android:textStyle">bold</item>
        <item name="fontPath">fonts/proxima-nova-bold.otf</item>
    </style>

**Comment by chrisjenx** [comment]
To be honest with you I've never tried that setup. Setting fontPath inside
a theme by its self probably won't do anything.

You need to set the fontPath on the textStyle then set that on the theme.

As for the error its throwing up, I'm not sure.

If you want to set the font on the toolbar styles you'll need to set the
fontPath on the actionbarTitleApperance.
