### ISSUE TITLE
Custom Layout Crash InflateException

### ISSUE THREAD

**Issue by marcoRS** [chrisjenx/Calligraphy#131]
Hello Chris, just wanted to start off by saying thanks for such a great library! With that in mind I'm hoping this crash report helps improve it. 

I'm currently seeing a crash on a couple of Samsung devices where the apps are crashing in what seems to be a failure to inflate a xml file used in a custom layout that extends FrameLayout. Below is the stack trace I've collected:

android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:626)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:675)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.view.View.inflate(View.java:18474)
       at re.snapwi.ui.RetryLayout.init(RetryLayout.java:52)
       at re.snapwi.ui.RetryLayout.<init>(RetryLayout.java:31)
       at re.snapwi.ui.photo.PhotoGalleryFragment.onCreateView(PhotoGalleryFragment.java:116)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5602)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:600)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:675)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:700)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
       at android.view.View.inflate(View.java:18474)
       at re.snapwi.ui.RetryLayout.init(RetryLayout.java:52)
       at re.snapwi.ui.RetryLayout.<init>(RetryLayout.java:31)

Line 52 of RetryLayout is calling inflate in the custom framelayout:

    private void init(Context context) {
        setLayoutTransition(new LayoutTransition());
        inflate(context, R.layout.retry_framelayout, this); // This is LINE 52
        progressLayout = findViewById(R.id.retryProgressLayout);
        progressBarDefault = findViewById(R.id.retryProgress);
       topProgressBar = findViewById(R.id.smoothProgressBar);

       retryLayout = findViewById(R.id.retryButtonLayout);
       mainLayout = (FrameLayout) findViewById(R.id.mainContent);
       retryTextView = (TextView) findViewById(R.id.retryTextView);
       retryTextView.setTextColor(retryTextColor);
       retryButton = (Button) findViewById(R.id.retryButton);
       mShortAnimationDuration = getResources().getInteger(android.R.integer.config_longAnimTime);
     }

The inflateException then points to Binary XML file line #63 which is the beginning of a ProgressBar tag

     <ProgressBar  
        android:id="@+id/retryProgress"
        style="@style/SnapwireSpinner"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:visibility="gone" />

The crash is affecting the following Samsung models: SM N910G, GT N7100, SCH S960L

**Comment by hateum** [comment]
Can you post the constructor of your custom layout ?
I had the same problem when I used a constructor without the default arguements.

PS: Sorry, I don't speak English very well.

**Comment by chrisjenx** [comment]
Your custom constructor HAS to have the two arg constructors! I get blamed for this, but it the issue lies with your implementation.

**Comment by chrisjenx** [comment]
If you remove Calligraphy you will see the same bug as an FYI.

**Comment by marcoRS** [comment]
Hey guys, I have the following constructors in the custom layout:

   public RetryLayout(Context context) {
       super(context);
       init(context);
     }

     public RetryLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
     }

      public RetryLayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init(context);
      }

       @TargetApi(Build.VERSION_CODES.LOLLIPOP) public RetryLayout(Context context, AttributeSet      attrs, int defStyleAttr, int defStyleRes) {
       super(context, attrs, defStyleAttr, defStyleRes);
       init(context);
       }

This crash only happens on  some Samsung devices and a category Crashlytics calls "Other".

**Comment by chrisjenx** [comment]
@marcoRS Personally whenever I write custom classes. I only provide the two arg constructor (saves you time!)

E.g.
```java
public RetryLayout(Context context, AttributeSet attrs) {
    super(context, attrs);
    init(context);
 }
```

If this works for every other device and not samsung, I would take a guess at this being an issue with your custom view and samsung devices and not calligraphy. We pass inflation off to the underling inflater. (We just get the blame for the exception).

**Comment by marcoRS** [comment]
That totally makes sense, thanks! I'll report back if I can figure out why these specific devices crash.

**Comment by chrisjenx** [comment]
@marcoRS sure, I'm wondering if I can maybe pass up the underlying exception. It's pretty unhelpful most of the time, if the Constructor causes a crash the stack is pretty useless :S

**Comment by marcoRS** [comment]
If that can be done it surely would be useful in debugging the problem. Samsung phones are going to be the death of me >.<

**Comment by chrisjenx** [comment]
Welcome to the club!

**Comment by matroska** [comment]
I have the same problem using a standard layout (no custom views)

android.view.LayoutInflater.createView (LayoutInflater.java:613)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView (CalligraphyLayoutInflater.java:162)
android.view.LayoutInflater.onCreateView (LayoutInflater.java:660)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView (CalligraphyLayoutInflater.java:146)
android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:685)
android.view.LayoutInflater.rInflate (LayoutInflater.java:746)
android.view.LayoutInflater.rInflate (LayoutInflater.java:749)
android.view.LayoutInflater.rInflate (LayoutInflater.java:749)
android.view.LayoutInflater.rInflate (LayoutInflater.java:749)
android.view.LayoutInflater.rInflate (LayoutInflater.java:749)
android.view.LayoutInflater.inflate (LayoutInflater.java:489)
uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate (CalligraphyLayoutInflater.java:60)
android.view.LayoutInflater.inflate (LayoutInflater.java:396)
android.view.LayoutInflater.inflate (LayoutInflater.java:352)
com.gromia.app2.ui.fragments.GromiaMapFragment.buildPreviews (GromiaMapFragment.java:564)
com.gromia.app2.ui.fragments.GromiaMapFragment.access$2000 (GromiaMapFragment.java:100)
com.gromia.app2.ui.fragments.GromiaMapFragment$14.onMarkerClick (GromiaMapFragment.java:980)
com.google.android.gms.maps.GoogleMap$10.a
android.os.Looper.loop (Looper.java:137)
android.app.ActivityThread.main (ActivityThread.java:4921)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)

**Comment by matroska** [comment]
<RelativeLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"

                    >

this is the line-->                    <ImageView
                        android:id="@+id/preview_image"
                        android:layout_width="135dp"
                        android:layout_height="match_parent"
                        android:layout_marginRight="5dp"
                        android:scaleType="centerCrop"
                        android:src="@drawable/house_example" />


android.view.InflateException: Binary XML file line #30: Error inflating class <unknown>

thanks a lot!

**Comment by chrisjenx** [comment]
@matroska does it work fine without calligraphy?

**Comment by matroska** [comment]
Yes, but it also work fine on non Samsung devices

**Comment by chrisjenx** [comment]
Ug, any specific samsung device? I'll see if I can replicate, but I would
guess its because Samsung (like usual) have a broken implementation.

**Comment by matroska** [comment]
Unfortunately it comes from Crashalytics, so I cannot replicate it either.
I can only see that it happens on galaxy s2 jelly bean 4.1.1 and on Note 2

**Comment by chrisjenx** [comment]
@matroska I've just seen something similar in our Crashlytics logs, I always pan these down to the devices. As the view that crashes the app is one that is used on hundreds of other devices fine. I've also see this on a Xiaomi device.

**Comment by matroska** [comment]
@chrisjenx thanks. Do you have any suggestion in order to avoid crashes? Can we disable Calligraphy on some specified views (and work in the traditional way)?

**Comment by chrisjenx** [comment]
@matroska do you have the full stack trace, as it should trace to what crashed in the `ImageView` to cause it.

**Comment by matroska** [comment]
android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
0android.view.LayoutInflater.createView LayoutInflater.java:613
1uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView CalligraphyLayoutInflater.java:162
2android.view.LayoutInflater.onCreateView LayoutInflater.java:660
3uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView CalligraphyLayoutInflater.java:146
4android.view.LayoutInflater.createViewFromTag LayoutInflater.java:685
5android.view.LayoutInflater.rInflate LayoutInflater.java:746
6android.view.LayoutInflater.rInflate LayoutInflater.java:749
7android.view.LayoutInflater.rInflate LayoutInflater.java:749
8android.view.LayoutInflater.rInflate LayoutInflater.java:749
9android.view.LayoutInflater.inflate LayoutInflater.java:489
10uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate CalligraphyLayoutInflater.java:60
11android.view.LayoutInflater.inflate LayoutInflater.java:396
12android.view.LayoutInflater.inflate LayoutInflater.java:352
13com.gromia.app2.ui.fragments.GromiaMapFragment.buildPreviews GromiaMapFragment.java:564
14com.gromia.app2.ui.fragments.GromiaMapFragment.access$2000 GromiaMapFragment.java:100
15com.gromia.app2.ui.fragments.GromiaMapFragment$14.onMarkerClick GromiaMapFragment.java:980
16com.google.android.gms.maps.GoogleMap$10.a Unknown Source
17com.google.android.gms.maps.internal.n$a.onTransact Unknown Source
18android.os.Binder.transact Binder.java:326
19com.google.android.gms.maps.internal.bd.a SourceFile:84
20com.google.maps.api.android.lib6.c.al.h Unknown Source
21com.google.maps.api.android.lib6.gmm6.c.h.a Unknown Source
22com.google.maps.api.android.lib6.gmm6.o.aw.a Unknown Source
23com.google.maps.api.android.lib6.gmm6.o.bf.a Unknown Source
24com.google.maps.api.android.lib6.gmm6.o.be.a Unknown Source
25com.google.maps.api.android.lib6.gmm6.o.bu.d Unknown Source
26com.google.maps.api.android.lib6.gmm6.o.ak.onSingleTapConfirmed Unknown Source
27com.google.maps.api.android.lib6.gmm6.i.g.onSingleTapConfirmed Unknown Source
28com.google.maps.api.android.lib6.gmm6.i.i.handleMessage Unknown Source
29android.os.Handler.dispatchMessage Handler.java:99
30android.os.Looper.loop Looper.java:137
31android.app.ActivityThread.main ActivityThread.java:4921
32java.lang.reflect.Method.invokeNative Native Method
33java.lang.reflect.Method.invoke Method.java:511
34com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run ZygoteInit.java:1027
35com.android.internal.os.ZygoteInit.main ZygoteInit.java:794
36dalvik.system.NativeStart.main Native Method
38java.lang.reflect.Constructor.constructNative Native Method
39java.lang.reflect.Constructor.newInstance Constructor.java:417
40android.view.LayoutInflater.createView LayoutInflater.java:587
43android.graphics.BitmapFactory.nativeDecodeAsset Native Method
44android.graphics.BitmapFactory.decodeStream BitmapFactory.java:625
45android.graphics.BitmapFactory.decodeResourceStream BitmapFactory.java:478
46android.graphics.drawable.Drawable.createFromResourceStream Drawable.java:781
47android.content.res.Resources.loadDrawable Resources.java:1963
48android.content.res.TypedArray.getDrawable TypedArray.java:601
49android.widget.ImageView.<init> ImageView.java:120
50android.widget.ImageView.<init> ImageView.java:110

**Comment by chrisjenx** [comment]
Mmm difficult. I can only assume that the Context gets messed on certain
devices where they have screwed with the inflater. Or maybe a race
condition. Until I have a device which I can replicate this on its going to
be nearly impossible.

**Comment by matroska** [comment]
Thanks. Is it possible to disable calligraphy on some layout in order to
avoid the problem? Thanks

Il giorno lun 16 feb 2015 19:39 Christopher Jenkins <
notifications@github.com> ha scritto:

**Comment by chrisjenx** [comment]
Not right now. You can of course exclude attach to base. In the activity
which is causing the problem. But nothing more granular then that.

**Comment by matroska** [comment]
I am using this to inflate LayoutInflater.from(activity).inflate(R.layout.element_preview_map, null);
is it possible to unwrap the context from the ContextWrapper in order to use original inflater?

**Comment by chrisjenx** [comment]
The point is that calligraphy uses the original inflater.
Is your fragment inside the layout? Or do you add it pragmatically.

**Comment by matroska** [comment]
I am fixing it in attachBaseContext(Context original)

I am saving in a field the original Context, so I can access it later doing
the LayoutInflation. It works because the font is the roboto one, so I can
exclude the problem.
I guess I can solve it in this way :)

Thanks

**Comment by marcoRS** [comment]
So I think I might have had a breakthrough in figuring out what the root problem is... I can create the exact same crash by making my app run out of memory. 

When the app is just about to run about memory and I try to load another view the app crashes with the same stack trace which at first appears to be caused by Calligraphy library but really it was because my app had a memory leak. 

At the very end of my stack trace I failed to notice:

Caused by: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:503)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:356)
       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:379)
       at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:409)
       at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:493)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:901)

Once I fixed this memory leak this crash went away. I hope this helps.

**Comment by chrisjenx** [comment]
Cool hopefully. Thanks! We'll leave it open a few days let me know if you
see it in wild again.

We need a better way of determining what the crash is and passing it on to
the stack trace.

**Comment by trolik** [comment]
I have the same problem on Samsung S5 (Genymotion)
 
android.view.InflateException: Binary XML file line #30: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at me.selfish.android.content.photo.gallery.PhotoAdapter.getView(PhotoAdapter.java:87)

**Comment by chrisjenx** [comment]
As stated above this is your view crashing. Calligraphy just gets blamed

**Comment by trolik** [comment]
Yeah, you are right! I've disabled calligraphy and got

 android.view.InflateException: Binary XML file line #30: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at me.selfish.android.content.photo.gallery.PhotoAdapter.getView(PhotoAdapter.java:87)

The strange thing XML is very simple, don't know why Samsung dont like it

**Comment by chrisjenx** [comment]
Yeah, not sure, Samsung always seem to break the CTS. Not sure why they are
allowed the Play Store. But thats a whole different argument.

**Comment by chrisjenx** [comment]
ReOpen if still not working with calligraphy disabled

**Comment by gvsharma** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.foyr.home_interiors/com.jbrinterio.roomagictapp.activities.MyDesignsActivity}: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2114)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
       at android.app.ActivityThread.access$700(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.view.InflateException: Binary XML file line #63: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate()
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImplV7.onCreate()
       at android.support.v7.app.AppCompatActivity.setContentView()
       at com.jbrinterio.roomagictapp.activities.MyDesignsActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:5203)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
       at android.app.ActivityThread.access$700(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate()
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImplV7.onCreate()
       at android.support.v7.app.AppCompatActivity.setContentView()
       at com.jbrinterio.roomagictapp.activities.MyDesignsActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:5203)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
       at android.app.ActivityThread.access$700(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)
       at android.content.res.Resources.loadDrawable(Resources.java:2822)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.view.View.(View.java:3419)
       at android.view.ViewGroup.(ViewGroup.java:432)
       at android.widget.LinearLayout.(LinearLayout.java:176)
       at android.widget.LinearLayout.(LinearLayout.java:172)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:593)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView()
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate()
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at android.support.v7.app.AppCompatDelegateImplV7.onCreate()
       at android.support.v7.app.AppCompatActivity.setContentView()
       at com.jbrinterio.roomagictapp.activities.MyDesignsActivity.onCreate()
       at android.app.Activity.performCreate(Activity.java:5203)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
       at android.app.ActivityThread.access$700(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)

i am getting this error? save me

**Comment by chrisjenx** [comment]
Nothing to do with Calligraphy, you have a broken view.

**Comment by jishindev** [comment]
Having trouble with a Samsung device (obvious) running 4.4, seem to be working fine on all other devices 

Stacktrace - 
```
Caused by: android.view.InflateException: 
 
  at android.view.LayoutInflater.createViewFromTag (LayoutInflater.java:719)
 
  at android.view.LayoutInflater.rInflate (LayoutInflater.java:761)
 
  at android.view.LayoutInflater.inflate (LayoutInflater.java:498)
 
  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate (CalligraphyLayoutInflater.java:60)
 
  at android.view.LayoutInflater.inflate (LayoutInflater.java:398)
 
  at com.dropnotesapp.android.notes.ui.fragments.NotesListFragment.onCreateView (NotesListFragment.java:222)
 
  at android.support.v4.app.Fragment.performCreateView (Fragment.java:2248)
 
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1340)
 
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1569)
 
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1636)
 
  at android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java:758)
 
  at android.support.v4.app.FragmentManagerImpl.executeOps (FragmentManager.java:2415)
 
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2201)
 
  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps (FragmentManager.java:2155)
 
  at android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2064)
 
  at android.support.v4.app.FragmentController.execPendingActions (FragmentController.java:379)
 
  at android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:607)
 
  at android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:178)
 
  at com.dropnotesapp.android.notes.ui.activities.MainActivity.onStart (MainActivity.java:103)
 
  at android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1177)
 
  at android.app.Activity.performStart (Activity.java:5468)
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2386)
```
