### ISSUE TITLE
Issue with Urban Airship 5.1

### ISSUE THREAD

**Issue by tommytcchan** [chrisjenx/Calligraphy#153]
Hi there,

The instructions says to override the ```attachBaseContext``` method, like so:

```
    super.attachBaseContext(CalligraphyContextWrapper.wrap(base));
```

However, I am using Urban Airship and when I start the app it gives me this error:

```
03-30 16:01:01.621  26230-26230/com.adhoclabs.burner E/Crittercism﹕ java.lang.RuntimeException: Unable to start receiver com.urbanairship.push.GCMPushReceiver: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2675)
            at android.app.ActivityThread.access$1800(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2657)
            at android.app.ActivityThread.access$1800(ActivityThread.java:175)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5602)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)
```

Has anyone experienced the same thing?

**Comment by sinoohe** [comment]
I have the same issue. I have overridden attachbaseContext method in the Application class,
if I override it on activity classes it works fine, but I use fragments and I have to override it even on Application class which it conflicts with Parse.
please help.

**Comment by chrisjenx** [comment]
@tommytcchan as @sinoohe said, **only** attach this in your activity.

**Comment by AshishPsaini** [comment]
I am facing issue in Broadcast receiver , app crashes when my Alarm broadcast receiver run .
Please help to resolve this Calligraphy library issue .

**Comment by chrisjenx** [comment]
Stack trace?
Why is Calligraphy at fault?
