### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{}: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>

### ISSUE THREAD

**Issue by varis** [chrisjenx/Calligraphy#159]
from time to time I see that crash with calligraphy on android emulator sdk 10
I am using NavigationDrawerFragment from Android example

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.imvu.mobilecordova/com.imvu.scotch.MainActivity}: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2832)
            at android.app.ActivityThread.access$1600(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:518)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at com.imvu.scotch.NavigationDrawerFragment.onCreateView(NavigationDrawerFragment.java:153)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:922)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1114)
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2195)
            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:297)
            at android.support.v7.app.ActionBarActivity.onCreateView(ActionBarActivity.java:543)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory.onCreateView(CalligraphyLayoutInflater.java:241)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:276)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.imvu.scotch.MainActivity.onCreate(MainActivity.java:74)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1611)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:2832)
            at android.app.ActivityThread.access$1600(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:415)
            at android.view.LayoutInflater.createView(LayoutInflater.java:505)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:568)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:386)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at com.imvu.scotch.NavigationDrawerFragment.onCreateView(NavigationDrawerFragment.java:153)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:922)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1114)
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2195)
            at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:297)
            at android.support.v7.app.ActionBarActivity.onCreateView(ActionBarActivity.java:543)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory.onCreateView(CalligraphyLayoutInflater.java:241)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
```

**Comment by consp1racy** [comment]
Does it still crash if you don't use Calligraphy?

Test by removing this from your activity:

    @Override
    protected void attachBaseContext(Context newBase) {
        // for custom fonts auto loading
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase));
    }

If the app still crashes, this problem is not related to Calligraphy.

**Comment by varis** [comment]
It didn't crash before Calligraphy and started after so ,I believe, the problem is related to Calligraphy

**Comment by consp1racy** [comment]
Well, some people believe in unicorns. Did you test it?

Looks like calligraphy is handing off work to platform inflater which fails ultimately. There appears to be something wrong with `NavigationDrawerFragment` layout root element. Can you share the first couple of lines from that layout?

**Comment by chrisjenx** [comment]
@varis I don't want to pass blame, but there is likely to be an issue in that views constructor, and unfortunately Calligraphy gets the blame (As it is the LayoutInflater to touch it last).

**Comment by Euphrates-Media** [comment]
Now it's working well using v 2.1.0
Thanks everybody

**Comment by ericn37** [comment]
I'm using v2.2.0 and it's happening to me
this has the most number of occurrences compared all other crashes in my app :(

**Comment by chrisjenx** [comment]
@ericn37 look at the stack trace and see where it starts. These start with the view constructor and code that is executed from the Android framework not Calligraphy.
