### ISSUE TITLE
ViewStub inflating crash

### ISSUE THREAD

**Issue by n-belokopytov** [chrisjenx/Calligraphy#165]
This is the viewstub

                <ViewStub
                    android:id="@+id/stub_nearby_dishes_1"
                    android:inflatedId="@+id/nearby_dishes_1"
                    android:layout="@layout/dish_preview"
                    android:layout_width="0dp"
                    android:layout_weight="0.5"
                    android:layout_marginRight="6dp"
                    android:layout_marginLeft="6dp"
                    android:layout_height="@dimen/home_card_height" />

Here is the crash:
android.view.InflateException: Binary XML file line #65: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

It is on Android 5.0.1 on HTC M8.

**Comment by n-belokopytov** [comment]
Fixed in 2.1.0
