### ISSUE TITLE
HockeyApp trying to create an AlertDialog causes IllegalStateException: A factory has already been set on this LayoutInflater

### ISSUE THREAD

**Issue by dkokic** [chrisjenx/Calligraphy#167]
```
05-08 17:17:23.678  27048-27048/de.audi.rse E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to resume activity {de.audi.rse/de.audi.rse.MainActivity}: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2826)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
            at android.app.ActivityThread.access$600(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:150)
            at android.app.ActivityThread.main(ActivityThread.java:5147)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
            at android.view.LayoutInflater.setFactory(LayoutInflater.java:277)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory(CalligraphyLayoutInflater.java:85)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setUpLayoutFactories(CalligraphyLayoutInflater.java:77)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>(CalligraphyLayoutInflater.java:44)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.cloneInContext(CalligraphyLayoutInflater.java:49)
            at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:113)
            at com.android.internal.app.AlertController$AlertParams.<init>(AlertController.java:914)
            at android.app.AlertDialog$Builder.<init>(AlertDialog.java:375)
            at android.app.AlertDialog$Builder.<init>(AlertDialog.java:360)
            at net.hockeyapp.android.CrashManager.showDialog(CrashManager.java:377)
            at net.hockeyapp.android.CrashManager.execute(CrashManager.java:183)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:125)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:101)
            at de.audi.rse.MainActivity.checkForCrashes(MainActivity.java:187)
            at de.audi.rse.MainActivity.onResume(MainActivity.java:183)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1185)
            at android.app.Activity.performResume(Activity.java:5216)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2816)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2855)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
            at android.app.ActivityThread.access$600(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:150)
            at android.app.ActivityThread.main(ActivityThread.java:5147)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by chrisjenx** [comment]
Make sure you are using `v2.1.0` this has already been fixed.

**Comment by YixinZhu** [comment]
I'm also running into this and I have updated to v2.1.0

error:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{Activity}: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
at android.view.LayoutInflater.setFactory2(LayoutInflater.java:305)
at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory2(CalligraphyLayoutInflater.java:96)
at android.support.v4.view.LayoutInflaterCompatLollipop.setFactory(LayoutInflaterCompatLollipop.java:24)
at android.support.v4.view.LayoutInflaterCompat$LayoutInflaterCompatImplV21.setFactory(LayoutInflaterCompat.java:49)
at android.support.v4.view.LayoutInflaterCompat.setFactory(LayoutInflaterCompat.java:79)
at android.support.v4.app.Fragment.getLayoutInflater(Fragment.java:936)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:501)
at android.app.Activity.performStart(Activity.java:5949)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
... 10 more
```

**Comment by YixinZhu** [comment]
Nevermind I had to clean my gradle cache and rebuild. @dkokic hopefully that works for you too

**Comment by chrisjenx** [comment]
This is a bug with hockey app. Either pass a cloned context to hockyapp or
raise a bug and point them in my direction.

**Comment by chrisjenx** [comment]
OK good to know.
