### ISSUE TITLE
IllegalStateException: A factory has already been set on this LayoutInflater

### ISSUE THREAD

**Issue by dkokic** [chrisjenx/Calligraphy#168]
```
05-08 18:11:23.758  18695-18695/de.audi.rse E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
            at android.view.LayoutInflater.setFactory(LayoutInflater.java:277)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setFactory(CalligraphyLayoutInflater.java:85)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.setUpLayoutFactories(CalligraphyLayoutInflater.java:77)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.<init>(CalligraphyLayoutInflater.java:44)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.cloneInContext(CalligraphyLayoutInflater.java:49)
            at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:113)
            at android.view.LayoutInflater.from(LayoutInflater.java:210)
            at android.support.v7.internal.view.menu.ListMenuPresenter.<init>(ListMenuPresenter.java:69)
            at android.support.v7.internal.app.ToolbarActionBar.ensureListMenuPresenter(ToolbarActionBar.java:528)
            at android.support.v7.internal.app.ToolbarActionBar.getListMenuView(ToolbarActionBar.java:495)
            at android.support.v7.internal.app.ToolbarActionBar.access$400(ToolbarActionBar.java:50)
            at android.support.v7.internal.app.ToolbarActionBar$ToolbarCallbackWrapper.onCreatePanelView(ToolbarActionBar.java:555)
            at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1058)
            at android.support.v7.app.AppCompatDelegateImplV7.onKeyDownPanel(AppCompatDelegateImplV7.java:1200)
            at android.support.v7.app.AppCompatDelegateImplV7.onKeyDown(AppCompatDelegateImplV7.java:756)
            at android.support.v7.app.AppCompatDelegateImplV7.dispatchKeyEvent(AppCompatDelegateImplV7.java:731)
            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImplBase.java:238)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:49)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1856)
            at android.view.ViewRootImpl.deliverKeyEventPostIme(ViewRootImpl.java:3715)
            at android.view.ViewRootImpl.handleImeFinishedEvent(ViewRootImpl.java:3665)
            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:2825)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:150)
            at android.app.ActivityThread.main(ActivityThread.java:5147)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by squeeish** [comment]
Are you using the latest AppCompat v7? It's v22.1.1 as of now.

**Comment by dkokic** [comment]
I was on 22.1.0 ... will try the latest version now.

**Comment by squeeish** [comment]
I only got this issue when I was using AppCompat v22.0.0 and the latest version of Calligraphy.

**Comment by saiimons** [comment]
Just had the same with 22.1.1.
Happened when adding a Fragment in an Activity.

**Comment by squeeish** [comment]
Are you using any other libraries like MaterialDialogs or MaterialEditText?

**Comment by dkokic** [comment]
The strange thing is that now the first activity is okay, but the second activity is failing (even thought all activities use fragments and extend AppCompatActivity). I understand that the context wrapping is neccessary in all activities, right?
I use appcompat-v7:22.1.1 and recyclerview-v7:22.1.0 ... additionally I use net.yanzm:mth:1.0.4 (MaterialTabHost) but in the 3rd activity (which doesn't get reached due to the crash).

**Comment by saiimons** [comment]
I am using https://github.com/wrapp/floatlabelededittext/ in my app.

**Comment by chrisjenx** [comment]
@saiimons are you using `v2.1.0`?

**Comment by chrisjenx** [comment]
Sorry that was directed at @dkokic .

**Comment by twilly86** [comment]
Not sure if this is related but I'm getting this error.  Error happens just by including the calligraphy dependency in my gradle file.

```
05-12 10:02:54.990    5140-5140/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: demo.alpinemetrics.com.myapplication, PID: 5140
    java.lang.StackOverflowError: stack size 8MB
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:890)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:321)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:85)
            at android.support.v7.app.AppCompatDelegateImplV7.onTitleChanged(AppCompatDelegateImplV7.java:494)
            at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:400)
            at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:171)
            at android.support.v7.a
```

**Comment by chrisjenx** [comment]
Are you using 2.1.x?

**Comment by twilly86** [comment]
Ignore my comment, it was related to AppCompat and not Calligraphy

**Comment by chrisjenx** [comment]
This is a broken constructor on one of your views

**Comment by dkokic** [comment]
Problems disappeared after migrating to v2.1.0 ;-)
