### ISSUE TITLE
Add custom font for application using Calligraphy for MaterialViewPager

### ISSUE THREAD

**Issue by srikanthnama** [chrisjenx/Calligraphy#178]
I am getting this issue when trying to apply custom font for my application. I am using MaterialViewPager.

I have mentioned the below lines in my theme, still getting this error. I tried without the Calligraphy, it is working fine. Problem when i added Calligraphy only.
name="windowActionBar" false
name="windowNoTitle" true

06-03 09:16:47.812 2100-2100/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.github.florent37.materialviewpager.sample, PID: 2100
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.florent37.materialviewpager.sample/com.github.florent37.materialviewpager.sample.MainActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalArgumentException: AppCompat does not support the current theme features
at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:360)
at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
at com.github.florent37.materialviewpager.sample.MainActivity.onCreate(MainActivity.java:52)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by chrisjenx** [comment]
At a guess `AppCompat does not support the current theme features` is your issue.

Lack of app: or android: I think.

**Comment by srikanthnama** [comment]
I was using this for my other projects which uses the same app compat
theme. Its working fine. Only problem with the material view pager, I have
raised a bug in it also, can you please try to resolve it.

**Comment by chrisjenx** [comment]
@srikanthnama can you give me a full example then so I can reproduce. Thanks.
