### ISSUE TITLE
Error when try to copy text from EditText

### ISSUE THREAD

**Issue by damiandzierzak92** [chrisjenx/Calligraphy#240]
When I try to copy text from EditText I'm getting error:

    android.view.InflateException: Binary XML file line #17: Error inflating class TextView
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
     at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
     at android.widget.Editor$ActionPopupWindow.initContentView(Editor.java:2972)
     at android.widget.Editor$PinnedPopupWindow.<init>(Editor.java:2267)
     at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2945)
     at android.widget.Editor$ActionPopupWindow.<init>(Editor.java:2945)
     at android.widget.Editor$HandleView.showActionPopupWindow(Editor.java:3165)
     at android.widget.Editor$SelectionModifierCursorController.initHandles(Editor.java:3689)
     at android.widget.Editor$SelectionModifierCursorController.show(Editor.java:3660)
     at android.widget.Editor$SelectionActionModeCallback.onCreateActionMode(Editor.java:2895)
     at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onCreateActionMode(PhoneWindow.java:2811)
     at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:155)
     at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onCreateActionMode(AppCompatDelegateImplV7.java:1695)
     at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionModeFromWindow(AppCompatDelegateImplV7.java:759)
     at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionMode(AppCompatDelegateImplV7.java:653)
     at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:74)
     at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:58)
     at android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode(WindowCallbackWrapper.java:145)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2432)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2419)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:689)
     at android.view.View.startActionMode(View.java:4561)
     at android.widget.Editor.startSelectionActionMode(Editor.java:1583)
     at android.widget.Editor.performLongClick(Editor.java:876)
     at android.widget.TextView.performLongClick(TextView.java:8585)
     at android.view.View$CheckForLongPress.run(View.java:18756)
     at android.os.Handler.handleCallback(Handler.java:808)
     at android.os.Handler.dispatchMessage(Handler.java:103)
     at android.os.Looper.loop(Looper.java:193)
     at android.app.ActivityThread.main(ActivityThread.java:5292)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
     at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: length=15; index=960
     at android.content.res.StringBlock.get(StringBlock.java:65)
     at android.content.res.XmlBlock$Parser.getPooledString(XmlBlock.java:458)
                                                                          	at android.content.

This is happening only on Lenovo Vertis 4010 with Android 4.4

**Comment by chrisjenx** [comment]
Does this happen when `Calligraphy` is off?

**Comment by chrisjenx** [comment]
Actualy closing, nothing to do with `Calligraphy`, probably a broken impl on that device. We are just the only identifiable trace in that stack.
