### ISSUE TITLE
Crash in CalligraphyLayoutInflater when inflating custom view in Android 4.1

### ISSUE THREAD

**Issue by ygnessin** [chrisjenx/Calligraphy#242]
Below is a `ClassCastException` stack trace coming from an `EditText` being inflated with `CalligraphyLayoutInflater` while inflating a custom view that I've built called `LocationEntryView`. I've been seeing this crash in the wild in my production app. I have not seen the crash locally so unfortunately I do not know how to reproduce. However Crashlytics does tell me that this only affects Android 4.1 users (and maybe earlier - 4.1 is lowest version my app supports).

I suppose it's possible that this crash is not a Calligraphy issue, but because it involves text views, strings, and `Editable`s and occurs during inflation, this is currently my best guess. Furthermore, I wasn't seeing this crash until I added Calligraphy to my app.

My Calligraphy version is `2.1.1-SNAPSHOT`

Thank you for helping me look into this. And thanks for all the work you put into making this fantastic library.

```
Caused by java.lang.ClassCastException: java.lang.String cannot be cast to android.text.Editable
       at android.widget.EditText.getText(EditText.java:75)
       at android.widget.EditText.getText(EditText.java:50)
       at android.widget.TextView.setTextIsSelectable(TextView.java:4673)
       at android.widget.TextView.(TextView.java)
       at android.widget.EditText.(EditText.java)
       at android.widget.EditText.(EditText.java)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at android.view.View.inflate(View.java:16237)
       at com.myapp.myapp.views.widgets.LocationEntryView.init(LocationEntryView.java:75)
       at com.myapp.myapp.views.widgets.LocationEntryView.(LocationEntryView.java)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.myapp.myapp.fragments.WelcomeFragment.onCreateView(WelcomeFragment.java:50)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:831)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1037)
       at android.app.BackStackRecord.run(BackStackRecord.java:635)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1399)
       at android.app.Activity.performStart(Activity.java:5075)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$600(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5520)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by chrisjenx** [comment]
Not to fob you off, but the chances of it being `Calligraphy` are almost nil. If you can reproduce it locally **and** it doesn't happen with Calligraphy off, then we get into some interesting territory.

Generally once you have a enough users and random devices using your App you see all sorts of weird issues. 

I think I see this sometimes if you paste text into EditText on older devices.

Anyway, the only thing Calligraphy actually does is `setTypeface()` on that `TextView` - it could be related (in the fact that setting Typeface on pre 4.1 devices has a bug...??)

**Comment by ygnessin** [comment]
Thanks for the fast response @chrisjenx. I tried a few different things before opening the issue for this exact reason, but I really appreciate the 2nd opinion. I'll give reproducing the error a few more shots (thanks for the tip on pasting text) and update this issue if I find anything

**Comment by jimitpatel** [comment]
Even I have the similar problem. I am using `CustomTextView` which calls my API internally. But it's crashing on `createView()` method which is within `CalligraphyLayoutInflater`. But for me stack is different. It is showing 
`android.view.InflateException: Binary XML file line #70:`

Any alternative to use custom views with this library?

Checklist which I followed for using this library

- [ ] In `Application` class, used `initDefault()` method for setting default font and font attribute id

- [ ] in `Activity` class, overridden `attachBaseContent()` method to use `super.attachBaseContent(CalligraphyContextWrapper,wrap(newBase))`

- [ ] In `style.xml`, font's path set for different fonts for parent `@android:style/TextAppearance` with `<item name="fontPath">@string/font_path</item>`. Which is working on non custom views.

- [ ] In layout file, `textAppearance` attribute is used for setting the font defined in `style.xml`

**Comment by chrisjenx** [comment]
Any thing which mentions: `android.view.InflateException: Binary XML file
line #70:` means your View has an invalid constructor.

**Comment by ygnessin** [comment]
@chrisjenx Thanks for the great library. I don't remember how I ended up resolving this old issue but I'm going to assume that you're right about this not being a Calligraphy problem. Closing.
