### ISSUE TITLE
"You must supply a layout_height attribute" Crash

### ISSUE THREAD

**Issue by PatrickDattilio** [chrisjenx/Calligraphy#243]
I've been getting a handful of crashes with over 80% of them coming from the OnePlusOne device

`Fatal Exception: java.lang.RuntimeException: Binary XML file line #153: You must supply a layout_height attribute.
       at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:606)
       at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6474)
       at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6642)
       at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1244)
       at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1084)
       at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:83)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.evilapples.app.fragments.game.CardsFragment.onCreateView(CardsFragment.java:266)
       at android.app.Fragment.performCreateView(Fragment.java:2053)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:834)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.Fragment.performStart(Fragment.java:2074)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:922)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.app.BackStackRecord.run(BackStackRecord.java:834)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5294)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)`

This looks like I simply missed setting `layout_height` in my xml, but I went through every single element and they all have a height set. I can't replicate this on any of my devices or emulators, but it's definitely reproducible for a handful of OnePlusOne users.

**Comment by chrisjenx** [comment]
Does this happen when `Calligraphy` is turned off?

**Comment by chrisjenx** [comment]
This probably isn't Calligraphy, LayoutInflater crashes just blame calligraphy annoyingly.
