### ISSUE TITLE
Class Cast Exception Crash

### ISSUE THREAD

**Issue by aditya2592** [chrisjenx/Calligraphy#249]
Hi Developers,

I have received the following crash from one of my apps using Calligraphy that are in production. It occurs only for a single device type (Everglow D35 running Android 4.2.2) - 

Any idea what this is about ?

java.lang.RuntimeException: Unable to start receiver com.google.android.gms.measurement.AppMeasurementReceiver: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl 

App trace :
`java.lang.RuntimeException: Unable to start receiver com.google.android.gms.measurement.AppMeasurementReceiver: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2580)
	at android.app.ActivityThread.access$1700(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: uk.co.chrisjenx.calligraphy.CalligraphyContextWrapper cannot be cast to android.app.ContextImpl
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2561)
	... 10 more`

**Comment by dallasgutauckis** [comment]
This is the same as #211, you have a broadcast receiever, it appears to be from Google Analytics.
