### ISSUE TITLE
Can't create asset from *******

### ISSUE THREAD

**Issue by matthewkrueger** [chrisjenx/Calligraphy#281]
Hi - thanks for the great library.  It's working really well - however...

Every single time my app starts, I see this exception:

> 04-25 14:31:40.778 5057-5057/com.mycompany.app W/Calligraphy: Can't create asset from ဒါက သင့် မိုဘိုင်း အကောင့် အတွက်  ကုန်ကျမှု ရှိလာနိုင်သည်။. Make sure you have passed in the correct path and file name.
>                                                                                java.lang.RuntimeException: Font asset not found ဒါက သင့် မိုဘိုင်း အကောင့် အတွက်  ကုန်ကျမှု ရှိလာနိုင်သည်။
>                                                                                    at android.graphics.Typeface.createFromAsset(Typeface.java:190)
>                                                                                    at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
>                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
>                                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
>                                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
>                                                                                    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>                                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
>                                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>                                                                                    at com.mycompany.app.LoginFragment.onCreateView(LoginFragment.java:51)
>                                                                                    at android.app.Fragment.performCreateView(Fragment.java:2220)
>                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
>                                                                                    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
>                                                                                    at android.app.BackStackRecord.run(BackStackRecord.java:793)
>                                                                                    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
>                                                                                    at android.app.FragmentController.execPendingActions(FragmentController.java:325)
>                                                                                    at android.app.Activity.performStart(Activity.java:6267)
>                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
>                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>                                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
>                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                    at android.os.Looper.loop(Looper.java:148)
>                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                                    at java.lang.reflect.Method.invoke(Native Method)
>                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Note that every time the app starts, the random file in a random language is different.  Also, note I am definitely not loading any of these random fonts - only a default ttf that I initialize properly in the Application class as the default font.  I have no clue what "ဒါက သင့် မိုဘိုင်း အကောင့် အတွက် ကုန်ကျမှု ရှိလာနိုင်သည်။" is.  And that file name changes frequently.

What's going on here?  The fact that I get a different error every time I run the app is bewildering - the fact that the font files are in languages that I can't even identify, even more so.  Thanks!

**Comment by chrisjenx** [comment]
Yeah, I think this is a packaging issue, I've seen other similar ones. Make sure multidex is up to date, using the latest build tools, gradle plugin etc...

**Comment by NeveHanter** [comment]
I'm also facing similar problem (I'm using gradle 2.14, latest build tools, targets API 24, and not using multidex at all)

> 06-25 23:19:43.013 3211-3211/com.example.fonts W/Calligraphy: Can't create asset from Palieskite, kad įves. slaptaž.. Make sure you have passed in the correct path and file name.
                                                             java.lang.RuntimeException: Font asset not found Palieskite, kad įves. slaptaž.
                                                                 at android.graphics.Typeface.createFromAsset(Typeface.java:206)
                                                                 at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                 at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                 at com.example.fonts.landing.LandingPageActivity.onCreate(LandingPageActivity.java:27)
                                                                 at android.app.Activity.performCreate(Activity.java:6658)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2584)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2692)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6044)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

And I've found that this line https://github.com/chrisjenx/Calligraphy/blob/master/calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyUtils.java#L191 fetches `Palieskite, kad įves. slaptaž`

**Comment by chrisjenx** [comment]
Well I wonder if some broken device ignore the attribute set that you request so I actually need to find the style index.

Tell me how to reproduce this and I can fix it.

**Comment by baneizalfe** [comment]
Just run the app, it happens to me too. 

`Can't create asset from res/drawable/ic_lock_idle_alarm.xml. Make sure you have passed in the correct path and file name. java.lang.RuntimeException: Font asset not found res/drawable/ic_lock_idle_alarm.xml`

Sometimes it is random string from support libraries

**Comment by chrisjenx** [comment]
You are going to have to be waaaaaay more specifc than that.

Device/Android
Version/BuildTools/Gradle/TargetSDK/CompileSDK/AppCompatVersion/Layout and
Styles XML/Font used.... etc.

This is used in some very big apps without issue, so it must be a weird
combination of things which most people don't use.

**Comment by baneizalfe** [comment]
> You are going to have to be waaaaaay more specifc than that.

> But that's the point. It is so random that you can not be specific. It seems like it gets confused with generated resourceId or similar. It is working, but this warning is still anoying

**Comment by shaildyp** [comment]
I had this issue with `AlertDialog`, Changing the `Context` from `Activity` to `ThemedContex` in the `Builder` seems fix the problem.

`new AlertDialog.Builder(getSupportActionBar().getThemedContext(), R.style.DialogThemeLight)`

**Comment by yincrash** [comment]
On my N5X running Nougat
```
W/Calligraphy: Can't create asset from यामुळे आपल्या मोबाईल खात्यावर शुल्क आकारले जाऊ शकते.. Make sure you have passed in the correct path and file name.
                                                                       java.lang.RuntimeException: Font asset not found यामुळे आपल्या मोबाईल खात्यावर शुल्क आकारले जाऊ शकते.
                                                                           at android.graphics.Typeface.createFromAsset(Typeface.java:206)
                                                                           at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                                                                           at uk.co.chrisjenx.calligraphy.CalligraphyFactory$ToolbarLayoutListener.onGlobalLayout(CalligraphyFactory.java:236)
                                                                           at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2107)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

This is in my integration though. I can't seem to recreate it in the sample app.

**Comment by rocket-andrew** [comment]
Can't create asset from res/{any}.xml. Make sure you have passed in the correct path and file name.
                                                                     java.lang.RuntimeException: Font asset not found res/drawable/stat_sys_battery_charge.xml
                                                                         at android.graphics.Typeface.createFromAsset(Typeface.java:206)
                                                                         at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                                                                         at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                                                                         at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                                                                         at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                                                                         at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                                                                         at uk.co.chrisjenx.calligraphy.CalligraphyFactory$ToolbarLayoutListener.onGlobalLayout(CalligraphyFactory.java:236)
                                                                         at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:912)

**Comment by radon** [comment]
@chrisjenx i created a sample project who recreate this problem. You can see it here https://github.com/radon/TestCalligraphy

**Comment by intrepidkarthi** [comment]
Here is what I see. I am using build tools `25.0.2` also I am using latest `MultiDex` library. I am running it on a Nexus5X - Nougat.

 `W/Calligraphy: Can't create asset from res/drawable/progress_horizontal.xml. Make sure you have passed in the correct path and file name.
                                              java.lang.RuntimeException: Font asset not found res/drawable/progress_horizontal.xml
                                                  at android.graphics.Typeface.createFromAsset(Typeface.java:284)
                                                  at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                  at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:211)
                                                  at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:269)
                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:178)
                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:100)
                                                  at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:652)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                  at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                  at android.app.Activity.performCreate(Activity.java:6912)
                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2900)
05-02 15:51:49.657 5168-5168/? W/Calligraphy:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3008)
                                                  at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                  at android.os.Looper.loop(Looper.java:154)
                                                  at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
05-02 15:51:49.658 5168-5168/? W/ResourceType: Too many attribute references, stopped at: 0x010102c5`

**Comment by chrisjenx** [comment]
This is either a multi dex or build tool issue. Again unrelated to
Calligraphy, we don't see these errors, check all your libaries are up to
date, your build targets match, your targeting the latest SDK etc

**Comment by royalhacker** [comment]
W/Calligraphy: Can't create asset from Забыли имя пользователя или пароль?
                                              Перейдите на страницу google.com/accounts/recovery.. Make sure you have passed in the correct path and file name.
                                              java.lang.RuntimeException: Font asset not found Забыли имя пользователя или пароль?
                                              Перейдите на страницу google.com/accounts/recovery.
                                                  at android.graphics.Typeface.createFromAsset(Typeface.java:198)
                                                  at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                  at android.view.LayoutInflater.inflate(<Xposed>)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                  at android.support.design.internal.NavigationMenuPresenter.inflateHeaderView(NavigationMenuPresenter.java:211)
                                                  at android.support.design.widget.NavigationView.inflateHeaderView(NavigationView.java:269)
                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:178)
                                                  at android.support.design.widget.NavigationView.<init>(NavigationView.java:100)
                                                  at java.lang.reflect.Constructor.newInstance(Native Method)
                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                  at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:754)
                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                  at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                  at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
                                                  at android.view.LayoutInflater.inflate(<Xposed>)
                                                  at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                  at com.armscon.activity.MainActivity.onCreate(MainActivity.java:42)
                                                  at android.app.Activity.performCreate(Activity.java:6251)
                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
                                              	at android.app.ActivityThread.handleLaunchActivity(ActivityT




I too am having the same problem

**Comment by RushiMThakker** [comment]
No I still have the issue. It's not with fonts folder location.

**Comment by chrisjenx** [comment]
Have you tried V3?

**Comment by luanmm** [comment]
Tried today with v3, but it still doesn't work. The problem seems to be the same as the issues filed because of tabs/actionbar styling (i.e. #401 #325 #390 #126). Calligraphy can't handle at all this use cases, when some component is created nested to the one that specifies text appearance.

This error message is because Calligraphy can't get font path from any of its sources. This is a sample:

	<android.support.design.widget.TabLayout
		style="@style/CustomTabLayout"
		fontPath="fonts/gotham_rnd_medium.otf"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		app:tabGravity="fill"
		app:tabMode="scrollable" />

The "fontPath" attribute in this case shouldn't even be necessary, but it is just another unsuccessful attempt.

There is no way for Calligraphy to get the correct font path to create the tabs' TextViews in that cases. It seems to be something that the library may handle, because it is used a lot.

The library does it job really well in other use cases, and is definitely a good option to customize fonts in an Android project. But IMHO if it helps me only partially, it doesn't help me at all. My point here is not only to criticize, but to expose something that seems to be a big problem for a lot of people that use support libraries (that seems to be the big problem here, because components aren't created in a trivial way).
