### ISSUE TITLE
Crashes on API 15+

### ISSUE THREAD

**Issue by JovieBrett** [chrisjenx/Calligraphy#286]
My app crashes on API 15 but not on API 21+ due to the Calligraphy lib that I'm using on the CardView's TextViews, any idea how to fix it and what really causes the problem?

```
android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v7.widget.CardView
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                                               at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                               at com.app.jovie.canteen.adapters.MyRecyclerAdapter.onCreateViewHolder(MyRecyclerAdapter.java:35)
                                                                               at com.app.jovie.canteen.adapters.MyRecyclerAdapter.onCreateViewHolder(MyRecyclerAdapter.java:22)
                                                                               at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5482)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4707)
                                                                               at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4617)
                                                                               at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1994)
                                                                               at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1390)
                                                                               at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1353)
                                                                               at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3028)
                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2906)
                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:953)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1695)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:122)
                                                                               at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                               at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1170)
                                                                               at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:814)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:953)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1187)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:460)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1687)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1545)
                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1450)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:460)
                                                                               at android.view.View.layout(View.java:13923)
                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4472)
                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1687)
                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.
```

**Comment by davidargylethacker** [comment]
Was there any solution to this? I'm running into the same issue? Was it just something simple?
