### ISSUE TITLE
NoClassDefFoundError - VectorDrawableCompat - Samsung Galaxy Tab 3 - Android Support Library 23.4.0

### ISSUE THREAD

**Issue by Mathbl** [chrisjenx/Calligraphy#291]
Maybe a long shot, but I decided to update appcompat/design/support libraries to latest version (23.4.0) and my app crashes on start on a Galaxy Tab 3 running android 5.0.2.

Stack trace seems to be related to calligraphy, but it may be something else too.

```java                                  
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{com.myapp.android/com.myapp.android.activities.MainActivity}: 
android.view.InflateException: Binary XML file line #1: Error inflating class android.support.v7.widget.Toolbar
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:181)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6134)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                                       Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class android.support.v7.widget.Toolbar
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                          at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:178)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:740)
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:904)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.myapp.android.activities.MainActivity.onCreate(MainActivity.java:97)
                                                                          at android.app.Activity.performCreate(Activity.java:6374)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:181) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:145) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6134) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                          at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:178) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:740) 
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:904) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.myapp.android.activities.MainActivity.onCreate(MainActivity.java:97) 
                                                                          at android.app.Activity.performCreate(Activity.java:6374) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:181) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:145) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6134) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
                                                                       Caused by: java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                          at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:891)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:356)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                          at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                                          at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                                          at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                          at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:178) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:740) 
                                                                          at android.view.LayoutInflater.parseInclude(LayoutInflater.java:904) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.myapp.android.activities.MainActivity.onCreate(MainActivity.java:97) 
                                                                          at android.app.Activity.performCreate(Activity.java:6374) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
                                                                          at android.app.ActivityThread.access$900(ActivityThread.java:181) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:145) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6134) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```

Just in case, here's my toolbar XML layout:
```XML
<android.support.v7.widget.Toolbar
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:myapp="http://schemas.android.com/apk/res-auto"
    android:id="@+id/toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:background="?attr/colorPrimary"
    android:gravity="center_vertical"
    myapp:contentInsetLeft="@dimen/content_spacing_normal"
    myapp:contentInsetRight="@dimen/content_spacing_normal"
    >

    <TextView
        android:id="@+id/toolbar_title"
        android:layout_width="wrap_content"
        android:layout_height="fill_parent"
        android:gravity="center_vertical"
        android:maxLines="1"
        android:ellipsize="end"
        android:textAppearance="?android:attr/textAppearanceLarge"
        android:textSize="@dimen/font_size_toolbar"
        android:textColor="@color/white"
        />

</android.support.v7.widget.Toolbar>
```

**Comment by chrisjenx** [comment]
Looks like a bug in 23.4:
```
Caused by: java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                          at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:891)
```

**Comment by Mathbl** [comment]
Yeah, that's what I thought, but I wanted your feedback just in case. I could report it on AOSP. It's just weird that nobody reported it at this time. Thanks!

**Comment by chrisjenx** [comment]
@Mathbl cool, post the issue on here so others can upvote.

**Comment by Mathbl** [comment]
Issue is there: https://code.google.com/p/android/issues/detail?id=209840

I'm noob to code.google, so I copy/pasted the code from my issue here and it didn't format/highlight correctly. And it doesn't seem possible to edit on google code.

![oh god why](http://orig01.deviantart.net/f7ad/f/2013/219/2/9/oh_god_why_in_hd_by_lemmino-d61t8ou.png)

**Comment by chrisjenx** [comment]
Nice one.

**Comment by wuknife** [comment]
maybe some help.
http://stackoverflow.com/questions/37423493/error-inflating-class-collapsingtoolbarlayout
