### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by HumnoyCmDev** [chrisjenx/Calligraphy#293]
Fatal Exception: java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:636)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:484)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:813)
       at android.content.res.Resources.loadDrawable(Resources.java:2822)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.ImageView.<init>(ImageView.java:126)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:57)
       at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:53)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
       at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
       at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1031)
       at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:280)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:681)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.humnoy.dev.thairathmini2016.fragment.WebViewFragment.onCreateView(WebViewFragment.java:138)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
       at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1178)
       at android.app.Activity.performStart(Activity.java:5213)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2087)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
       at android.app.ActivityThread.access$700(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4960)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by chrisjenx** [comment]
@HumnoyCmDev yeah, thats an OOM error. nothing to do with Calligraphy.
