### ISSUE TITLE
Cut or copy using the Clipboard crashes the app. 

### ISSUE THREAD

**Issue by droidizer** [chrisjenx/Calligraphy#308]
Hello,

I have a strange issue in some Samsung devices. When I try to cut or copy in an edit text the app crashes. The following is the log. Just want to check if it is an issue with the library. 

Thanks a  bunch.
Sowmya.

android.view.InflateException: Binary XML file line #27: Error inflating class TextView
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:770)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                                             at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
                                                                             at android.widget.Toast.makeText(Toast.java:308)
                                                                             at android.widget.Toast.makeText(Toast.java:366)
                                                                             at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:153)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
                                                                          Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 24
                                                                             at android.content.res.TypedArray.getColor(TypedArray.java:403)
                                                                             at android.widget.TextView.<init>(TextView.java:1077)
                                                                             at android.widget.TextView.<init>(TextView.java:994)
                                                                             at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:60)
                                                                             at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:56)
                                                                             at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:980)
                                                                             at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1039)
                                                                             at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                                                                             at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:280)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:732)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                                             at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
                                                                             at android.widget.Toast.makeText(Toast.java:308) 
                                                                             at android.widget.Toast.makeText(Toast.java:366) 
                                                                             at android.sec.clipboard.ClipboardExManager$1.handleMessage(ClipboardExManager.java:153) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:145) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by droidizer** [comment]
Looks like it still does after removing the library so closing this issue.

**Comment by chrisjenx** [comment]
yeah someone else raised this. Deffo a Samwang bug.

**Comment by Rishabh-sx** [comment]
Hi All , this issue arise when we have `android:theme="@style/TextInputStyle"` in textInputLayout , so after removing this , your app will not crash.

**Comment by ghost** [comment]
Hello, I got the same error and the solution was to remove this

       ` <item name = "android: fontFamily"> sans-serif </ item>`

of my styles and better configure the Theme of my app

**Comment by dishantkawatra** [comment]
1. Copy your code of textinput layout style and paste in your Apptheme 
2. Remove style from textinput layout
