### ISSUE TITLE
Warning when using it with betterpickers library

### ISSUE THREAD

**Issue by BradleyRL** [chrisjenx/Calligraphy#32]
I'm getting the following warning on a project, just wondering if anyone knows why and how to get rid of it, my project works fine :)

The warning fires every time i open a dialog created with betterpickers https://github.com/derekbrameyer/android-betterpickers

04-21 16:10:27.356: W/Calligraphy(1496): Can't create asset from sans-serif-light. Make sure you have passed in the correct path and file name.
04-21 16:10:27.356: W/Calligraphy(1496): java.lang.RuntimeException: native typeface cannot be made
04-21 16:10:27.356: W/Calligraphy(1496):    at android.graphics.Typeface.<init>(Typeface.java:147)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.graphics.Typeface.createFromAsset(Typeface.java:121)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:33)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:30)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:42)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:116)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onCreateView(CalligraphyFactory.java:65)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:669)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
04-21 16:10:27.356: W/Calligraphy(1496):    at com.doomonafireball.betterpickers.numberpicker.NumberPicker.<init>(NumberPicker.java:75)
04-21 16:10:27.356: W/Calligraphy(1496):    at java.lang.reflect.Constructor.constructNative(Native Method)
04-21 16:10:27.356: W/Calligraphy(1496):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.createView(LayoutInflater.java:586)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.createViewOrFailQuietly(CalligraphyFactory.java:89)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.createViewOrFailQuietly(CalligraphyFactory.java:73)
04-21 16:10:27.356: W/Calligraphy(1496):    at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onCreateView(CalligraphyFactory.java:61)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:669)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
04-21 16:10:27.356: W/Calligraphy(1496):    at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
04-21 16:10:27.356: W/Calligraphy(1496):    at com.doomonafireball.betterpickers.numberpicker.NumberPickerDialogFragment.onCreateView(NumberPickerDialogFragment.java:143)

**Comment by ayz4sci** [comment]
Hi,

I'm getting this same error. I have checked the following:
Your font is in the assets folder.
Your path is correct. assets/fonts/Typeface.ttf would equal fonts/Typeface.tff in Calligraphy.
Your your extension is correct, you can't omit the file extension, (leave ttf/otf) on the end.
Check case, Android is a case sensitive file system

But still getting the error. Btw, I'm using Material Design.

com.deliveryscience.ughelistock W/Calligraphy﹕ Can't create asset from fonts/avenir-light.ttf. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: native typeface cannot be made
            at android.graphics.Typeface.<init>(Typeface.java:307)
            at android.graphics.Typeface.createFromAsset(Typeface.java:281)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:123)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:144)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:173)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:131)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at com.deliveryscience.ughelistock.SplashLogin.onCreate(SplashLogin.java:67)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5283)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)

**Comment by chrisjenx** [comment]
Someone else reported this. It appeared that the .ttf was corrupt or not
compatible with Android (does happen sometimes.)

If the the error is reporting the file path correctly is generally out of
Calligraphies reach as we wrap the `Typeface.createFromAsset()`.

Just double check your .ttf (I still do it as .tff sometimes).
Try another opentype font (Roboto etc, they always work).
