### ISSUE TITLE
On some devices, it reports 'Error inflating class android.webkit.WebView'.

### ISSUE THREAD

**Issue by breezehou** [chrisjenx/Calligraphy#324]
Device: SM-T211
Android OS: 4.1.2
Logs:
java.lang.NullPointerException
	at android.webkit.WebSettingsClassic.getDefaultUserAgentForLocale(WebSettingsClassic.java:583)
	at android.webkit.WebSettingsClassic.getCurrentUserAgent(WebSettingsClassic.java:474)
	at android.webkit.WebSettingsClassic.<init>(WebSettingsClassic.java:372)
	at android.webkit.WebViewCore.<init>(WebViewCore.java:225)
	at android.webkit.WebViewClassic.init(WebViewClassic.java:2892)
	at android.webkit.WebView.<init>(WebView.java:521)
	at android.webkit.WebView.<init>(WebView.java:491)
	at android.webkit.WebView.<init>(WebView.java:472)
	at android.webkit.WebView.<init>(WebView.java:461)
	at com.example.EnhancedWebView.<init>(EnhancedWebView.java:30)
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:593)
	at uk.co.chrisjenx.calligraphy.d.a(CalligraphyLayoutInflater.java:211)
	at uk.co.chrisjenx.calligraphy.d.a(CalligraphyLayoutInflater.java:20)
	at uk.co.chrisjenx.calligraphy.d$a.onCreateView(CalligraphyLayoutInflater.java:302)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:686)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:460)
	at uk.co.chrisjenx.calligraphy.d.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        ... ...

**Comment by chrisjenx** [comment]
That NPE originates from your WebView, nothing to do with Calligraphy.

**Comment by breezehou** [comment]
Hi chrisjenx, when I replace with system webview widget, it is still crashed.

**Comment by chrisjenx** [comment]
Remove Calligraphy and let me know if it still happens.

**Comment by breezehou** [comment]
It's ok after remove Calligraphy. Can we deliver webview construction to the default LayoutInflater?

**Comment by chrisjenx** [comment]
Give me the code and device so I can reproduce, I have a feeling this is a
device bug we'll need to work around.

**Comment by breezehou** [comment]
I just use Calligraphy in demo project, it is ok. I will check why it is failed in our project.

**Comment by breezehou** [comment]
It is our bug, fixed.
