### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by LeeeYudE** [chrisjenx/Calligraphy#331]
When I installed the app MI Pad, there has been NoClassDefFoundError, how to solve this problem?
```
 java.lang.NoClassDefFoundError: uk.co.chrisjenx.calligraphy.R$attr
                                                       at uk.co.chrisjenx.calligraphy.CalligraphyConfig$Builder.<init>(CalligraphyConfig.java:194)
                                                       at com.charco.ve.MyApplication.onCreate(VEApplication.java:76)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4355)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:139)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5028)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by LeeeYudE** [comment]
I think I found the reason, the method number more than 65k as my app, After I quoted the multidex was no errors

**Comment by chrisjenx** [comment]
This is a build error/multidex error, Generally update your build tools and this will go away. (And include multidex correctly)
