### ISSUE TITLE
Can't create asset from res/anim/activity_close_exit.xml. Make sure you have passed in the correct path and file name.

### ISSUE THREAD

**Issue by ericn37** [chrisjenx/Calligraphy#344]
I've seen this warning for the longest time.
My code does not use any `activity_close_exit.xml` animation at all:
```
W/Calligraphy: Can't create asset from res/anim/activity_close_exit.xml. Make sure you have passed in the correct path and file name.
               java.lang.RuntimeException: Font asset not found res/anim/activity_close_exit.xml
                   at android.graphics.Typeface.createFromAsset(Typeface.java:190)
                   at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:35)
                   at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:114)
                   at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:143)
                   at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:146)
                   at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
                   at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                   at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                   at android.support.design.widget.TabLayout$TabView.update(TabLayout.java:1537)
                   at android.support.design.widget.TabLayout$TabView.setTab(TabLayout.java:1484)
                   at android.support.design.widget.TabLayout$TabView.access$700(TabLayout.java:1348)
                   at android.support.design.widget.TabLayout.createTabView(TabLayout.java:799)
                   at android.support.design.widget.TabLayout.newTab(TabLayout.java:500)
                   at android.support.design.widget.TabLayout.populateFromPagerAdapter(TabLayout.java:773)
                   at android.support.design.widget.TabLayout.setPagerAdapter(TabLayout.java:764)
                   at android.support.design.widget.TabLayout.setupWithViewPager(TabLayout.java:716)
                   at com.sephora.digital.views.activities.HomeActivity.initSlidingTabs(HomeActivity.java:353)
                   at com.sephora.digital.views.activities.HomeActivity.onCategoriesFetched(HomeActivity.java:414)
                   at com.sephora.digital.caches.CategoriesCache.fetchFromCache(CategoriesCache.java:43)
                   at com.sephora.digital.views.activities.HomeActivity.onCreate(HomeActivity.java:99)
                   at android.app.Activity.performCreate(Activity.java:6285)
                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
                   at android.app.ActivityThread.access$900(ActivityThread.java:154)
                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
                   at android.os.Handler.dispatchMessage(Handler.java:102)
                   at android.os.Looper.loop(Looper.java:234)
                   at android.app.ActivityThread.main(ActivityThread.java:5526)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ppietak** [comment]
I've encountered a similar problem, but in my case RuntimeException had message `native typeface cannot be made`. It turned out, that when I removed `<item name="fontPath">` from my "main custom app theme", it didn't show up anymore.
So, anyone: if you have a similar exception, try not using `fontPath` in global app theme.

**Comment by pcg92** [comment]
same problem, nice answer

**Comment by Llorc** [comment]
On my side the problem was with the location of the 'assets' folder. 
Once I put it as sibling of the 'res' folder under common parent .../src/main
all was fine again :)

**Comment by luanmm** [comment]
The main problem seems to be with some cache handled by some build tool. I had this problem too, but just doing a clean/rebuild solved it.
