### ISSUE TITLE
android.view.InflateException: Binary XML file line #101: Error inflating class eu.fiskur.markdownview.MarkdownView

### ISSUE THREAD

**Issue by felixeduardo15** [chrisjenx/Calligraphy#356]
Devices: Samsung, ZTE, LGE.
SO: 5.1.1, 5.1, 5.0.2

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{}: android.view.InflateException: Binary XML file line #101: Error inflating class eu.fiskur.markdownview.MarkdownView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by android.view.InflateException: Binary XML file line #101: Error inflating class eu.fiskur.markdownview.MarkdownView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at MainActivity.onStart(SourceFile:885)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at MainActivity.onStart(SourceFile:885)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by android.view.InflateException: Binary XML file line #7: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at eu.fiskur.markdownview.MarkdownView.setup(SourceFile:96)
       at eu.fiskur.markdownview.MarkdownView.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at eu.fiskur.markdownview.MarkdownView.setup(SourceFile:96)
       at eu.fiskur.markdownview.MarkdownView.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2185)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2180)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2239)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at eu.fiskur.markdownview.MarkdownView.setup(SourceFile:96)
       at eu.fiskur.markdownview.MarkdownView.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:114)
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:133)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.WebView.getFactory(WebView.java:2185)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2180)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2239)
       at android.view.View.(View.java)
       at android.view.View.(View.java)
       at android.view.ViewGroup.(ViewGroup.java)
       at android.widget.AbsoluteLayout.(AbsoluteLayout.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at android.webkit.WebView.(WebView.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(SourceFile:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at eu.fiskur.markdownview.MarkdownView.setup(SourceFile:96)
       at eu.fiskur.markdownview.MarkdownView.(SourceFile)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(SourceFile:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(SourceFile:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(SourceFile:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(SourceFile:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.support.v4.app.Fragment.performCreateView(SourceFile:2087)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1113)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1295)
       at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1277)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(SourceFile:2154)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(SourceFile:201)
       at android.support.v4.app.FragmentActivity.onStart(SourceFile:603)
       at android.support.v7.app.AppCompatActivity.onStart(SourceFile:181)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
       at android.app.Activity.performStart(Activity.java:6036)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
       at android.app.ActivityThread.access$800(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by chrisjenx** [comment]
Unrelated, bug in MarkdownView -> `android.view.InflateException: Binary XML file line #101: Error inflating class eu.fiskur.markdownview.MarkdownView` 

Stack traces stop at the place that caused it, Calligraphy is just IN the stack trace not the cause, this would be the same as blaming RxJava for an error inside your `subscriber`.
