### ISSUE TITLE
Crash that happens every so often: Failed to resolve TypedValue attribute

### ISSUE THREAD

**Issue by MKevin3** [chrisjenx/Calligraphy#366]
We see this reported by our HockeyApp crash reports in the field and I see it happen in the emulator ever once it a while. Unsure how to recreate it.

E/AndroidRuntime: FATAL EXCEPTION: main
                  android.view.InflateException: Binary XML file line #17: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff80cbc4 a=2 r=0x7f0e013a}
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                      at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:89)
                      at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:160)
                      at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:153)
                      at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187)
                      at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:286)
                      at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:171)
                      at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:803)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x1c/d=0xff80cbc4 a=2 r=0x7f0e013a}
                      at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:705)
                      at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6890)
                      at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7071)
                      at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:446)
                      at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:386)
                      at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:385)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:502)
                      at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at android.support.v7.view.menu.MenuAdapter.getView(MenuAdapter.java:89) 
                      at android.support.v7.view.menu.MenuPopup.measureIndividualMenuWidth(MenuPopup.java:160) 
                      at android.support.v7.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:153) 
                      at android.support.v7.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:187) 
                      at android.support.v7.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:286) 
                      at android.support.v7.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:171) 
                      at android.support.v7.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:803) 
                      at android.os.Handler.handleCallback(Handler.java:739) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by chrisjenx** [comment]
I've seen this caused by the build tools, once using the latest versions and matching up build tools to OS API versions these should disappear - either way, it's unrelated to Calligraphy, we just inflate it so we are in the stacktrace.
