### ISSUE TITLE
not workin on old 4.1

### ISSUE THREAD

**Issue by geniusforapp** [chrisjenx/Calligraphy#369]
android.view.InflateException: Binary XML file line #2: Error inflating class <unknown>
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164)
                                                                       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
                                                                       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                                                                       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                       at com.mikepenz.fastadapter.items.AbstractItem.getViewHolder(AbstractItem.java:239)
                                                                       at com.mikepenz.fastadapter.FastAdapter$OnCreateViewHolderListenerImpl.onPreCreateViewHolder(FastAdapter.java:1786)
                                                                       at com.mikepenz.fastadapter.FastAdapter.onCreateViewHolder(FastAdapter.java:440)
                                                                       at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6078)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5248)
                                                                       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
                                                                       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
                                                                       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
                                                                       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
                                                                       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3379)
                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3188)
                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3632)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.support.v4.widget.SlidingPaneLayout.onLayout(SlidingPaneLayout.java:725)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                       at android.view.View.layout(View.java:13754)
                                                                       at android.view.ViewGroup.layout(ViewGroup.java:4362)
                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1866)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1687)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                   	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreog

**Comment by chrisjenx** [comment]
You have a crash in one of your view constructors.
