### ISSUE TITLE
API 22 issues after updating to support libs 25.4.0

### ISSUE THREAD

**Issue by YmlMark** [chrisjenx/Calligraphy#394]
All good with devices running more recent API levels. However with API 22, looks like TextInputLayout and calligraphy are no longer friends.

E/AppCompatResources: Failed to inflate ColorStateList, leaving it to the framework
                                                                                    java.lang.RuntimeException: Failed to resolve attribute at index 0
                                                                                        at android.content.res.TypedArray.getColor(TypedArray.java:401)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.inflate(AppCompatColorStateListInflater.java:114)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXmlInner(AppCompatColorStateListInflater.java:88)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXml(AppCompatColorStateListInflater.java:67)
                                                                                        at android.support.v7.content.res.AppCompatResources.inflateColorStateList(AppCompatResources.java:116)
                                                                                        at android.support.v7.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:74)
                                                                                        at android.support.v7.widget.TintTypedArray.getColorStateList(TintTypedArray.java:136)
                                                                                        at android.support.v7.widget.AppCompatTextHelper.onSetTextAppearance(AppCompatTextHelper.java:157)
                                                                                        at android.support.v7.widget.AppCompatTextView.setTextAppearance(AppCompatTextView.java:148)
                                                                                        at android.support.v4.widget.TextViewCompatGingerbread.setTextAppearance(TextViewCompatGingerbread.java:103)
                                                                                        at android.support.v4.widget.TextViewCompat$BaseTextViewCompatImpl.setTextAppearance(TextViewCompat.java:86)
                                                                                        at android.support.v4.widget.TextViewCompat.setTextAppearance(TextViewCompat.java:283)
                                                                                        at android.support.design.widget.TextInputLayout.setErrorEnabled(TextInputLayout.java:609)
                                                                                        at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:253)
                                                                                        at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
                                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                                        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                        at com.firstrepublic.banking.ui.fragments.SignInFragment.onCreateView(SignInFragment.java:185)
                                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
                                                                                        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
                                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                                        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                                    	at android.app.Instrumenta
06-14 15:26:21.820 3214-3214/com.firstrepublic.banking.np2rc2 E/AppCompatResources: Failed to inflate ColorStateList, leaving it to the framework
                                                                                    java.lang.RuntimeException: Failed to resolve attribute at index 0
                                                                                        at android.content.res.TypedArray.getColor(TypedArray.java:401)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.inflate(AppCompatColorStateListInflater.java:114)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXmlInner(AppCompatColorStateListInflater.java:88)
                                                                                        at android.support.v7.content.res.AppCompatColorStateListInflater.createFromXml(AppCompatColorStateListInflater.java:67)
                                                                                        at android.support.v7.content.res.AppCompatResources.inflateColorStateList(AppCompatResources.java:116)
                                                                                        at android.support.v7.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:74)
                                                                                        at android.support.v7.widget.TintTypedArray.getColorStateList(TintTypedArray.java:136)
                                                                                        at android.support.v7.widget.AppCompatTextHelper.onSetTextAppearance(AppCompatTextHelper.java:157)
                                                                                        at android.support.v7.widget.AppCompatTextView.setTextAppearance(AppCompatTextView.java:148)
                                                                                        at android.support.v4.widget.TextViewCompatGingerbread.setTextAppearance(TextViewCompatGingerbread.java:103)
                                                                                        at android.support.v4.widget.TextViewCompat$BaseTextViewCompatImpl.setTextAppearance(TextViewCompat.java:86)
                                                                                        at android.support.v4.widget.TextViewCompat.setTextAppearance(TextViewCompat.java:283)
                                                                                        at android.support.design.widget.TextInputLayout.setErrorEnabled(TextInputLayout.java:609)
                                                                                        at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:253)
                                                                                        at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
                                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                                        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
                                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                        at com.firstrepublic.banking.ui.fragments.SignInFragment.onCreateView(SignInFragment.java:185)
                                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
                                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
                                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
                                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
                                                                                        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
                                                                                        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                                        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                                    	at android.app.Instrumenta

**Comment by plusema86** [comment]
Same error
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.quaestiones.quaestiones/com.quaestiones.quaestiones.activities.LoginActivity}: android.view.InflateException: Binary XML file line #103: Binary XML file line #103: Error inflating class android.support.design.widget.TextInputLayout
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by android.view.InflateException: Binary XML file line #103: Binary XML file line #103: Error inflating class android.support.design.widget.TextInputLayout

Caused by android.view.InflateException: Binary XML file line #103: Error inflating class android.support.design.widget.TextInputLayout

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
       at android.support.v7.app.m.b(AppCompatDelegateImplV9.java:292)
       at android.support.v7.app.e.setContentView(AppCompatActivity.java:140)
       at com.quaestiones.quaestiones.activities.LoginActivity.onCreate(LoginActivity.java:117)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by android.content.res.Resources$NotFoundException: Drawable com.quaestiones.quaestiones:drawable/design_password_eye with resource ID #0x7f0800a5

Caused by android.content.res.Resources$NotFoundException: File res/drawable-v21/design_password_eye.xml from drawable resource ID #0x7f0800a5
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:775)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
       at android.content.res.Resources.getDrawable(Resources.java:1640)
       at android.content.Context.getDrawable(Context.java:525)
       at android.support.v4.content.e.a(ContextCompatApi21.java:30)
       at android.support.v4.content.d.a(ContextCompat.java:372)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:202)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:190)
       at android.support.v7.c.a.b.b(AppCompatResources.java:100)
       at android.support.v7.widget.bj.a(TintTypedArray.java:71)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:237)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
       at android.support.v7.app.m.b(AppCompatDelegateImplV9.java:292)
       at android.support.v7.app.e.setContentView(AppCompatActivity.java:140)
       at com.quaestiones.quaestiones.activities.LoginActivity.onCreate(LoginActivity.java:117)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by android.view.InflateException: Class not found x
       at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:210)
       at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:132)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1251)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1224)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:765)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
       at android.content.res.Resources.getDrawable(Resources.java:1640)
       at android.content.Context.getDrawable(Context.java:525)
       at android.support.v4.content.e.a(ContextCompatApi21.java:30)
       at android.support.v4.content.d.a(ContextCompat.java:372)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:202)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:190)
       at android.support.v7.c.a.b.b(AppCompatResources.java:100)
       at android.support.v7.widget.bj.a(TintTypedArray.java:71)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:237)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
       at android.support.v7.app.m.b(AppCompatDelegateImplV9.java:292)
       at android.support.v7.app.e.setContentView(AppCompatActivity.java:140)
       at com.quaestiones.quaestiones.activities.LoginActivity.onCreate(LoginActivity.java:117)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.ClassNotFoundException: Didn't find class "x" on path: DexPathList[[zip file "/data/app/com.quaestiones.quaestiones-1/base.apk"],nativeLibraryDirectories=[/data/app/com.quaestiones.quaestiones-1/lib/arm64, /data/app/com.quaestiones.quaestiones-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:191)
       at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:132)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1251)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1224)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:765)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
       at android.content.res.Resources.getDrawable(Resources.java:1640)
       at android.content.Context.getDrawable(Context.java:525)
       at android.support.v4.content.e.a(ContextCompatApi21.java:30)
       at android.support.v4.content.d.a(ContextCompat.java:372)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:202)
       at android.support.v7.widget.k.a(AppCompatDrawableManager.java:190)
       at android.support.v7.c.a.b.b(AppCompatResources.java:100)
       at android.support.v7.widget.bj.a(TintTypedArray.java:71)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:237)
       at android.support.design.widget.TextInputLayout.<init>(TextInputLayout.java:183)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
       at android.view.LayoutInflater.createView(LayoutInflater.java:652)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
       at android.support.v7.app.m.b(AppCompatDelegateImplV9.java:292)
       at android.support.v7.app.e.setContentView(AppCompatActivity.java:140)
       at com.quaestiones.quaestiones.activities.LoginActivity.onCreate(LoginActivity.java:117)
       at android.app.Activity.performCreate(Activity.java:6942)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
