### ISSUE TITLE
android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.EditText

### ISSUE THREAD

**Issue by iad24** [chrisjenx/Calligraphy#417]
It happens to ZenFone 2 device, Android 5.0
Im using this lib version 2.3.0

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.yyy/com.myapp.modules.login.views.LoginActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.EditText
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2326)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.access$800(ActivityThread.java:147)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5264)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
Caused by android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.EditText
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:164)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:148)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

Full stack trace is here: 
[stacktrace.txt](https://github.com/chrisjenx/Calligraphy/files/1378419/stacktrace.txt)

Layout xml file of Login activity:
[activity_login.txt](https://github.com/chrisjenx/Calligraphy/files/1378428/activity_login.txt)

**Comment by vlad-cotfas** [comment]
I`m having the same issue..

**Comment by iad24** [comment]
It seems this library does not work well with TextInputLayout

```
<android.support.design.widget.TextInputLayout
        android:id="@+id/usernameLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:theme="@style/TextAppearance.TextInputLayout.Login"
        android:layout_marginBottom="@dimen/default_margin_3"
        android:layout_marginStart="@dimen/default_margin_3"
        android:layout_marginEnd="@dimen/default_margin_3"
        android:gravity="bottom"

        >

        <EditText
            android:id="@+id/usernameEditTxt"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="@dimen/default_margin_3"
            android:textSize="16sp"
            android:singleLine="true"
            android:textColor="@color/colorGrey3"
            android:hint="Username"
            android:text="dindun.test02+5003@gmail.com"
            android:inputType="textEmailAddress"
            />
    </android.support.design.widget.TextInputLayout>
```



style.xml
```
<style name="TextAppearance.TextInputLayout.Login">
        <item name="fontPath">fonts/font.ttf</item>
        <item name="android:textColorHint">@color/colorAccent2</item>
        <item name="colorAccent">@color/colorGrey4</item>
        <item name="colorControlNormal">@color/colorGrey6</item>
        <item name="colorControlActivated">@color/colorAccent2</item>
        <item name="android:textSize">16sp</item>
    </style>
```

If I remove the **android:theme in TextInputLayout**, the exception is gone.

**Comment by xPryds** [comment]
Same issue but with Buttons. 

` android.view.InflateException: Binary XML file line #0: Error inflating class Button`

Device: LG G3
Operating System: 4.4.2

`

Caused by android.content.res.Resources$NotFoundException
--
  | android.content.res.Resources.loadDrawable (Resources.java:2136)
  | android.support.v7.app.AppCompatDelegateImplV9.onCreateView (Unknown Source)
  | uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView (Unknown Source)
  | android.view.LayoutInflater$FactoryMerger.onCreateView (LayoutInflater.java:172)
  | android.view.LayoutInflater.inflate (LayoutInflater.java:492)
  | uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate (Unknown Source)
  | android.view.LayoutInflater.inflate (LayoutInflater.java:397)
  | com.buildone.delivery.features.profile.DriverProfileFragment.onCreateView (Unknown Source)
  | android.support.v4.app.Fragment.performCreateView (Unknown Source)
  | dalvik.system.NativeStart.main (NativeStart.java)



Caused by org.xmlpull.v1.XmlPullParserException
--
  | android.graphics.drawable.Drawable.createFromXmlInner (Drawable.java:933)
  | android.support.v7.app.AppCompatDelegateImplV9.onCreateView (Unknown Source)
  | uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView (Unknown Source)
  | android.view.LayoutInflater$FactoryMerger.onCreateView (LayoutInflater.java:172)
  | android.view.LayoutInflater.inflate (LayoutInflater.java:492)
  | uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate (Unknown Source)
  | android.view.LayoutInflater.inflate (LayoutInflater.java:397)
  | com.buildone.delivery.features.profile.DriverProfileFragment.onCreateView (Unknown Source)
  | android.support.v4.app.Fragment.performCreateView (Unknown Source)
  | dalvik.system.NativeStart.main (NativeStart.java)



EDIT:
My problem was using vector drawables in android buttons. Not related to calligraphy.

**Comment by swat-cat** [comment]
Same issue with LG H810 Android 5.1

**Comment by enriqkeg** [comment]
Same problem with LG k240h 6.0

**Comment by CaviaTheGuineaPig** [comment]
I had the same bug, and cause by the attribute "BackgroundTint" in the Floating button view

**Comment by Tizhoodh82** [comment]
I have same issue in SAMSUNG GLAXAY J5 .

**Comment by uliluck** [comment]
same issue in android studio 3.0
OS 4.4.2

**Comment by Sufi313** [comment]
/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.taggroup.www.darzeeco, PID: 3664
                                                                         android.view.InflateException: Binary XML file line #0: Error inflating class ImageButton
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                             at com.taggroup.www.darzeeco.CustomerAct.CartAdapter.onCreateViewHolder(CartAdapter.java:42)
                                                                             at com.taggroup.www.darzeeco.CustomerAct.CartAdapter.onCreateViewHolder(CartAdapter.java:27)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6519)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5706)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5589)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5585)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2231)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:610)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3135)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
                                                                             at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.widget.ScrollView.onMeasure(ScrollView.java:326)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                             at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                             at android.view.View.measure(View.java:16497)
                                                                             at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
                                                                             at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
                                                                             at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                         	at android

**Comment by Sufi313** [comment]
Hi! guys i have this error when i run application in kitkat i know multidex and i enabled but error show

**Comment by sshahidaslamm** [comment]
For Android Studio 3.0.1

I have got the same issue and I have resolved finally Opening the `gradle.properties` and added following line:

`android.enableAapt2=false`

**Comment by techview51** [comment]
Same issue: Solved.
My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.

**Comment by ariel179** [comment]
@techview51 you saved my life thank you!!!!

**Comment by RofaeilGerges** [comment]
@sshahidaslamm your solution solved my problem!

**Comment by techview51** [comment]
@ariel179 You are welcome.

**Comment by AdrianoJunior** [comment]
Same problem here but with Fragment.

**Comment by ghost** [comment]
@techview51 Copied and fixed, thank you so much!

**Comment by samk17cmutpm** [comment]
@techview51 Thank you so much !

**Comment by ghost** [comment]
@techview51 thanks a ton mate 🗡

**Comment by techview51** [comment]
@TBaulos , @samk17cmutpm , @UnselfconsciousLux : You are welcome.

**Comment by georgetsiga** [comment]
Also had the same ussue, I did what @techview51 said and it worked.

**Comment by allexiusw** [comment]
@techview51 thanks for solutions... very simple!

**Comment by CowardlyVillain** [comment]
me: FATAL EXCEPTION: main
                  Process: com.example.ennie.miniproject, PID: 15398
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ennie.miniproject/com.example.ennie.miniproject.LoginActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class Button
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5728)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class Button
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                      at com.example.ennie.miniproject.LoginActivity.onCreate(LoginActivity.java:26)
                      at android.app.Activity.performCreate(Activity.java:6371)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class Button
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.example.ennie.miniproject.LoginActivity.onCreate(LoginActivity.java:26) 
                      at android.app.Activity.performCreate(Activity.java:6371) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource "com.example.ennie.miniproject:drawable/shape" (7f070077) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f070077 a=-1 r=0x7f070077}
                      at android.content.res.Resources.loadDrawableForCookie(Resources.java:2899)
                      at android.content.res.Resources.loadDrawable(Resources.java:2821)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
                      at android.view.View.<init>(View.java:4001)
                      at android.widget.TextView.<init>(TextView.java:700)
                      at android.widget.Button.<init>(Button.java:109)
                      at android.widget.Button.<init>(Button.java:105)
                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:65)
                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:61)
                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
                      at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1023)
                      at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1080)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                      at com.example.ennie.miniproject.LoginActivity.onCreate(LoginActivity.java:26) 
                      at android.app.Activity.performCreate(Activity.java:6371) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5728) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by anshkumarsaha** [comment]
you need to change AppTheme @styles.xml like
its really work
<style name="AppTheme" parent="Theme.AppCompat.menuCompact">
to
<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">

**Comment by chrisjenx** [comment]
Interesting, appt2 shouldn't break this, we'll need to raise a bug report to see why it's doing it

**Comment by sdeff** [comment]
I'm having the same issue. The Android drawable "res/drawable-v21/design_password_eye.xml" is not found when inflating TextInputLayout on some devices with Android Lollipop and higher. The same happens with "Calligraphy 3".

**Comment by ghost** [comment]
@sshahidaslamm  i'll follow your answer but it's give me a new error android.view.InflateException: Binary XML file line #129: Error inflating class TextView.
On Emulator it's work perfectly without using your answer but in my device give me a error

**Comment by sanjayajena37** [comment]
I have Same problem but in Floating Action Button..And Navigation Bar

**Comment by sanjayajena37** [comment]
@techview51 Thanks bro..I complete my app successfully.Just Because of you.Again thanks bro.

**Comment by auzanassdq** [comment]
techview51 thanks dude

**Comment by auzanassdq** [comment]
@techview51 thanks dude..

**Comment by techview51** [comment]
@auzanassdq @sanjayajena37 @allexsv @georgetsiga
You are welcome.

**Comment by soheltanvir0699** [comment]
@techview51 thanks bro.....my problemis solve

**Comment by techview51** [comment]
@soheltanvir0699 You are welcome.

**Comment by PrajeetShrestha** [comment]
@techview51 Wasted 4 hours trying to solve the problem. The simple copy of image to drawable folder solved. But why does this work?

**Comment by zhengwu119** [comment]
@techview51 Thanks.

**Comment by 51600104** [comment]
@techview51 Are u a hero, sir ? , you just save my life !!!

**Comment by rpattabi** [comment]
In my case, I found that I shouldn't use attr / theme reference in color resource. For example, the following color resource caused the problem.

## Problem

```
<color name="title">?attr/colorSpecial</color>
<style name="mytheme" parent="xyz">
  <item name="colorAccent">@color/title</item>
</style>
```

## Solution
Don't use attribute / theme colors directly in color resource that may or may not be in turn used in theme.

```
<color name="title">@color/colorSpecial</color>
<style name="mytheme" parent="xyz">
  <item name="colorAccent">@color/title</item>
</style>
```
If you really need theme color (i.e. `?attr/xxx`), probably instead of regular color resource, you may need to define another color attribute in your theme.

**Comment by AnangNawawi** [comment]
@sshahidaslamm Thank you, you solved my problem

**Comment by JayTailor45** [comment]
> Same issue: Solved.
> My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.

You saved my life :+1:

**Comment by ruman86** [comment]
@rpattabi , You are right. Thanks.

Don't use attribute / theme colors directly in color resource that may or may not be in turn used in theme.

<color name="title">@color/colorSpecial</color>
<style name="mytheme" parent="xyz">
  <item name="colorAccent">@color/title</item>
</style>

If you really need theme color (i.e. ?attr/xxx), probably instead of regular color resource, you may need to define another color attribute in your theme.

**Comment by Chandrakala14** [comment]
I am facing the issue in textInputLayout Password field

Resource not found exception Drawable  drawable/design_password_eye with resource ID #0x7f080098

Please help me to solve this .

this is my build.gradle
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:support-core-ui:28.0.0'
    implementation 'com.android.support:support-vector-drawable:28.0.0'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
        }
```

**Comment by Moonlighter** [comment]
hi, all
I have the same issue when i use (Android 6):
On EditText:
- android:drawableStart
- android:background

And on RelativeLayout : 
- android:background
...
And when i copy resources from  drawable-v24 to drawable it's work fine .

Thank's @techview51

**Comment by techview51** [comment]
> @techview51 Wasted 4 hours trying to solve the problem. The simple copy of image to drawable folder solved. But why does this work?

I don't know exactly, just works ;)

**Comment by techview51** [comment]
> @techview51 Thanks.

You are welcome.

**Comment by techview51** [comment]
> @techview51 Are u a hero, sir ? , you just save my life !!!

Glad to hear that. Good luck.

**Comment by techview51** [comment]
> > Same issue: Solved.
> > My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.
> 
> You saved my life 👍

@JayTailor45 Glad to hear that. Good luck.

**Comment by techview51** [comment]
> hi, all
> I have the same issue when i use (Android 6):
> On EditText:
> 
> * android:drawableStart
> * android:background
> 
> And on RelativeLayout :
> 
> * android:background
>   ...
>   And when i copy resources from  drawable-v24 to drawable it's work fine .
> 
> Thank's @techview51

You are welcome.

**Comment by JwalaApporio** [comment]
Caused by: android.view.InflateException: Binary XML file line #54: Binary XML file line #54: Error inflating class EditText

I was also getting the similar error,
In my case I had added xml file's( icon) with drwable. By adding Normal png images solved the issue.

Adding xml files with drawable causes error many times, sometimes error does not come.

**Comment by naveedahmad99** [comment]
> copied

In my case, no drawable 24 folder exist, nor values and layout.

**Comment by Duna** [comment]
in my case I do not have drawable-24 or 21 in the project

**Comment by AhmedMahmoudRizk** [comment]
> Same issue: Solved.
> My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.

Thank you sir, it works fine
you save my time

**Comment by techview51** [comment]
> > Same issue: Solved.
> > My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.
> 
> Thank you sir, it works fine
> you save my time

You are welcome.

**Comment by aeonSolutions** [comment]
none of the above solutions solved the issue for me. 
I'm on android studio 4 canary 15.

**Comment by sangeet-shikha** [comment]
> Same issue: Solved.
> My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.

Thanks. This worked for me.

**Comment by techview51** [comment]
> > Same issue: Solved.
> > My image files were in the "drawable-v24" folder. I copied them to the "drawable" folder too. Problem solved.
> 
> Thanks. This worked for me.

You are welcome.

**Comment by AbdullahAbuMadi** [comment]
.

**Comment by AbdullahAbuMadi** [comment]
typedArray.recycle()//must be last line in init function

**Comment by FarhanaAkterSuci** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.example.smartalarm, PID: 8423
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.smartalarm/com.example.smartalarm.Activity2}: android.view.InflateException: Binary XML file line #15 in com.example.smartalarm:layout/activity_2: Binary XML file line #15 in com.example.smartalarm:layout/activity_2: Error inflating class fragment
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8309)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #15 in com.example.smartalarm:layout/activity_2: Binary XML file line #15 in com.example.smartalarm:layout/activity_2: Error inflating class fragment
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #15 in com.example.smartalarm:layout/activity_2: Error inflating class fragment
                                                                                                    Caused by: java.lang.NullPointerException
                                                                                                    	at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.Fragment.instantiate(Fragment.java:536)
                                                                                                    	at android.app.FragmentContainer.instantiate(FragmentContainer.java:53)
                                                                                                    	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3553)
                                                                                                    	at android.app.FragmentController.onCreateView(FragmentController.java:105)
                                                                                                    	at android.app.Activity.onCreateView(Activity.java:7264)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:300)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1096)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1024)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:988)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1150)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:709)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:775)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
                                                                                                    	at com.example.smartalarm.Activity2.onCreate(Activity2.java:13)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8176)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8143)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
2023-11-10 12:57:19.672  8423-8423  AndroidRuntime          com.example.smartalarm               E  	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8309)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
