### ISSUE TITLE
InflateException: Binary XML file line #0 - API 19

### ISSUE THREAD

**Issue by kamalnewscorp** [chrisjenx/Calligraphy#424]
Hi All,
I'm getting this below error while inflating a custom view in API 19 devices. 

````
android.view.InflateException: Binary XML file line #0: Error inflating class com.myapp.ui.customview
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:714)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
                                                                                at android.view.LayoutInflater.parseInclude(LayoutInflater.java:840)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
````

**Comment by chrisjenx** [comment]
Err looks like that class isn't on the class path in that case, check your naming and multidex.
