### ISSUE TITLE
AppCompatTextView is not supported with autoresize options

### ISSUE THREAD

**Issue by ddB0515** [chrisjenx/Calligraphy#428]
I'm having crashes with new support library and AppCompatTextView

this is XML

            <android.support.v7.widget.AppCompatTextView
                android:layout_width="match_parent"
                android:layout_height="@dimen/button_height_medium"
                android:background="@drawable/button_background_white"
                android:gravity="center"
                app:autoSizeTextType="uniform"
                app:autoSizeMinTextSize="@dimen/font_size_default"
                app:autoSizeMaxTextSize="@dimen/font_size_header"
                app:autoSizeStepGranularity="2sp"
                android:padding="@dimen/margin_half" />

But on latest version I'm getting crash (here is log)

FATAL EXCEPTION: main
                                                                Process: com.myapp.app, PID: 14513
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp.app/com.myapp.app.activities.SmartReadingPromptActivity}: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.AppCompatTextView
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2367)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:160)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5491)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                                 Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.support.v7.widget.AppCompatTextView
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:637)
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                                                                    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508)
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                    at com.myapp.app.activities.AbstractActivity.onCreate(AbstractActivity.java:68)
                                                                    at com.myapp.app.activities.AbstractToolbarActivity.onCreate(AbstractToolbarActivity.java:19)
                                                                    at android.app.Activity.performCreate(Activity.java:6010)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:160) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5491) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                                 Caused by: java.lang.reflect.InvocationTargetException
                                                                    at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:611)
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                    at com.myapp.app.activities.AbstractActivity.onCreate(AbstractActivity.java:68) 
                                                                    at com.myapp.app.activities.AbstractToolbarActivity.onCreate(AbstractToolbarActivity.java:19) 
                                                                    at android.app.Activity.performCreate(Activity.java:6010) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:160) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5491) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                                 Caused by: java.lang.IllegalArgumentException: Maximum auto-size text size (21.300001px) is less or equal to minimum auto-size text size (21.300001px)
                                                                    at android.support.v7.widget.AppCompatTextViewAutoSizeHelper.validateAndSetAutoSizeTextTypeUniformConfiguration(AppCompatTextViewAutoSizeHelper.java:488)
                                                                    at android.support.v7.widget.AppCompatTextViewAutoSizeHelper.loadFromAttributes(AppCompatTextViewAutoSizeHelper.java:167)
                                                                    at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:171)
                                                                    at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:81)
                                                                    at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:71)
                                                                    at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                    at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                    at android.view.LayoutInflater.createView(LayoutInflater.java:611) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302) 
                                                                    at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177) 
                                                                    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:737) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:810) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:508) 
                                                                    at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                    at com.myapp.app.activities.AbstractActivity.onCreate(AbstractActivity.java:68) 
                                                                    at com.myapp.app.activities.AbstractToolbarActivity.onCreate(AbstractToolbarActivity.java:19) 
                                                                    at android.app.Activity.performCreate(Activity.java:6010) 
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122) 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2320) 
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2435) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:160) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5491) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

any solution for this????

**Comment by aqhter** [comment]
I am also getting same issue !!!!
