### ISSUE TITLE
Fatal Exception: android.view.InflateException: in SimpleDraweeView when use fresco library for image 

### ISSUE THREAD

**Issue by SundusMoJW** [chrisjenx/Calligraphy#446]
Fatal Exception: android.view.InflateException: Binary XML file line #160: Binary XML file line #160: Error inflating class <unknown>
       at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
       at android.app.Dialog.setContentView(Dialog.java:837)
       at com.google.maps.android.clustering.view.DefaultClusterRenderer$1.onMarkerClick(DefaultClusterRenderer.java:147)
       at com.google.maps.android.MarkerManager.onMarkerClick(MarkerManager.java:103)
       at com.google.maps.android.clustering.ClusterManager.onMarkerClick(ClusterManager.java:211)
       at com.google.android.gms.maps.zzb.zza(Unknown Source)
       at com.google.android.gms.maps.internal.zzas.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:387)
       at fh.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):10)
       at com.google.android.gms.maps.internal.bi.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):5)
       at com.google.maps.api.android.lib6.impl.dd.b(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):39)
       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):63)
       at com.google.maps.api.android.lib6.gmm6.vector.m.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):97)
       at com.google.maps.api.android.lib6.gmm6.vector.af.c(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):204)
       at com.google.maps.api.android.lib6.gmm6.vector.cs.onSingleTapConfirmed(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):28)
       at com.google.maps.api.android.lib6.impl.gesture.h.onSingleTapConfirmed(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):266)
       at com.google.maps.api.android.lib6.impl.gesture.d.handleMessage(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):26)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7223)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)*
Caused by android.view.InflateException: Binary XML file line #160: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:657)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
       at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
       at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:474)
       at android.app.Dialog.setContentView(Dialog.java:837)
          at com.google.maps.android.clustering.view.DefaultClusterRenderer$1.onMarkerClick(DefaultClusterRenderer.java:147)
       at com.google.maps.android.MarkerManager.onMarkerClick(MarkerManager.java:103)
       at com.google.maps.android.clustering.ClusterManager.onMarkerClick(ClusterManager.java:211)
       at com.google.android.gms.maps.zzb.zza(Unknown Source)
       at com.google.android.gms.maps.internal.zzas.onTransact(Unknown Source)
       at android.os.Binder.transact(Binder.java:387)
       at fh.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):10)
       at com.google.android.gms.maps.internal.bi.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):5)
       at com.google.maps.api.android.lib6.impl.dd.b(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):39)
       at com.google.maps.api.android.lib6.gmm6.api.e.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):63)
       at com.google.maps.api.android.lib6.gmm6.vector.m.a(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):97)
       at com.google.maps.api.android.lib6.gmm6.vector.af.c(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):204)
       at com.google.maps.api.android.lib6.gmm6.vector.cs.onSingleTapConfirmed(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):28)
       at com.google.maps.api.android.lib6.impl.gesture.h.onSingleTapConfirmed(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):266)
       at com.google.maps.api.android.lib6.impl.gesture.d.handleMessage(:com.google.android.gms.dynamite_dynamitemodulesb@12529019@12.5.29 (040306-192802242):26)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7223)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by chrisjenx** [comment]
Nothing to do with calligraphy, looks like an xml issue.
