### ISSUE TITLE
The application stops

### ISSUE THREAD

**Issue by So47** [chrisjenx/Calligraphy#451]
05-20 19:38:20.160 14900-14900/com.example.sondo.swift E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.sondo.swift, PID: 14900
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.sondo.swift/com.example.sondo.swift.LoginActivity}: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class android.support.design.widget.TextInputLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: android.view.InflateException: Binary XML file line #24: Binary XML file line #24: Error inflating class android.support.design.widget.TextInputLayout
     Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class android.support.design.widget.TextInputLayout
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.design.widget.TextInputLayout" on path: DexPathList[[zip file "/data/app/com.example.sondo.swift-2/base.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.sondo.swift-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.sondo.swift-2/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.view.LayoutInflater.createView(LayoutInflater.java:609)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.sondo.swift.LoginActivity.onCreate(LoginActivity.java:31)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by chrisjenx** [comment]
Dex issue, update your multidex
