### ISSUE TITLE
nokia android 10

### ISSUE THREAD

**Issue by starritree** [chrisjenx/Calligraphy#479]
hello 
in android nokia 10 
after add this comment crash 
    override fun attachBaseContext(newBase: Context?) {
        super.attachBaseContext(CalligraphyContextWrapper.wrap(newBase))
   }
and this issue just happen in nokia android 10

**Comment by MukeshGreenDeveloper** [comment]
yes i too get the same issue
**`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.taxiapp/com.example.taxiapp.MainActivity}: android.view.InflateException: Binary XML file line #17 in com.example.taxiapp:layout/abc_screen_simple: Binary XML file line #17 in com.example.taxiapp:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout`**


`  Caused by: android.view.InflateException: Binary XML file line #17 in com.example.taxiapp:layout/abc_screen_simple: Binary XML file line #17 in com.example.taxiapp:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in com.example.taxiapp:layout/abc_screen_simple: Error inflating class androidx.appcompat.widget.FitWindowsLinearLayout
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
        at uk.co.chrisjenx.calligraphy.ReflectionUtils.getValue(ReflectionUtils.java:29)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:203)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)`

Device: Asus Zenfone Max M1
OS: Andorid 10

`**dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.navigation:navigation-fragment:2.1.0'
    implementation 'androidx.navigation:navigation-ui:2.1.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.2'

    //Add Library
    implementation 'com.google.firebase:firebase-auth:19.3.1'
    implementation 'com.google.firebase:firebase-storage:19.1.1'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.firebase:firebase-database:19.3.0'
    implementation 'com.github.d-max:spots-dialog:0.7@aar'
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.firebase:geofire-android:3.0.0'
    implementation 'com.github.glomadrian:MaterialAnimatedSwitch:1.1@aar'

    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.google.android.libraries.places:places:2.1.0'

    implementation 'com.google.firebase:firebase-messaging:20.2.0'
    implementation 'de.hdodenhof:circleimageview:2.2.0'


}
**`

**Comment by Mahdikh75** [comment]
yes i too get the same issue (Android 12 - Xiaomi)
