### ISSUE TITLE
Upgrading to Calligraphy3 (3.1.1) + ViewPump (2.0.3) causes Android app with API 28 or below to crash

### ISSUE THREAD

**Issue by Werone** [chrisjenx/Calligraphy#482]
@chrisjenx 
> What about the crash that older target sdk version apps are facing, if they update to Calligraphy 3?

No idea, but if it's problem still on ViewPump + Calligraphy 3 then we'll fix it over there. 👍

_Originally posted by @chrisjenx in https://github.com/chrisjenx/Calligraphy/issues/475#issuecomment-597805353_

Linked issue: https://github.com/InflationX/Calligraphy/issues/37

P.S: I am not using androidX

**Comment by Werone** [comment]
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/os/BuildCompat;
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.<init>(-ViewPumpLayoutInflater.kt:25)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:25)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:22)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getInflater(Unknown Source:7)
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getSystemService(ViewPumpContextWrapper.kt:31)
        at android.view.LayoutInflater.from(LayoutInflater.java:229)
        at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:167)
        at android.app.Activity.getSystemService(Activity.java:6024)
        at android.view.LayoutInflater.from(LayoutInflater.java:229)
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:305)
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:313)
        at android.app.Activity.attach(Activity.java:7055)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2873)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.os.BuildCompat" on path: DexPathList[[zip file "/data/app/com.adobe.creativesdk.sample-CQAQsge7XU_6jwzjJdLFWg==/base.apk"],nativeLibraryDirectories=[/data/app/com.adobe.creativesdk.sample-CQAQsge7XU_6jwzjJdLFWg==/lib/x86, /data/app/com.adobe.creativesdk.sample-CQAQsge7XU_6jwzjJdLFWg==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.<init>(-ViewPumpLayoutInflater.kt:25) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:25) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper$inflater$2.invoke(ViewPumpContextWrapper.kt:22) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getInflater(Unknown Source:7) 
        at io.github.inflationx.viewpump.ViewPumpContextWrapper.getSystemService(ViewPumpContextWrapper.kt:31) 
        at android.view.LayoutInflater.from(LayoutInflater.java:229) 
        at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:167) 
        at android.app.Activity.getSystemService(Activity.java:6024) 
        at android.view.LayoutInflater.from(LayoutInflater.java:229) 
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:305) 
        at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:313) 
        at android.app.Activity.attach(Activity.java:7055) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2873) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by chrisjenx** [comment]
Closing, dup of other issues. Update to Androidx. https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio

**Comment by FairMARYAM** [comment]
#
