### ISSUE TITLE
Not working in Lollipop and AppCompat library

### ISSUE THREAD

**Issue by ruqqq** [chrisjenx/Calligraphy#84]
On Android 4.4 with AppCompat Library, Calligraphy 1.1.+ doesn't work. However, Calligraphy 0.7.+ works fine.

On Android 5.0 with AppCompat Libary, both Calligraphy 1.1.+ and 0.7.+ does not seem to work.

**Comment by thearaks** [comment]
Hi @chrisjenx,
I'm testing Snapshot 2.0.0.
Everything seems ok, except some strange warnings when inflating options menus (might be support SearchView widget):
```
01-09 03:37:14.340    7137-7137/it.codeatlas.android.veecards W/Calligraphy﹕ Can't create asset from res/drawable-ldpi-v4/search_plate.9.png. Make sure you have passed in the correct path and file name.
    java.lang.RuntimeException: Font asset not found res/drawable-ldpi-v4/search_plate.9.png
            at android.graphics.Typeface.createFromAsset(Typeface.java:190)
            at uk.co.chrisjenx.calligraphy.TypefaceUtils.load(TypefaceUtils.java:34)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:112)
            at uk.co.chrisjenx.calligraphy.CalligraphyUtils.applyFontToTextView(CalligraphyUtils.java:141)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:173)
            at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:131)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.support.v7.widget.SearchView.<init>(SearchView.java:282)
            at android.support.v7.widget.SearchView.<init>(SearchView.java:268)
            at android.support.v7.widget.SearchView.<init>(SearchView.java:264)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.support.v7.internal.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:499)
            at android.support.v7.internal.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:458)
            at android.support.v7.internal.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:479)
            at android.support.v7.internal.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:196)
            at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:118)
            at it.codeatlas.android.veecards.NavigationActivity.onCreateOptionsMenu(NavigationActivity.java:484)
            at android.app.Activity.onCreatePanelMenu(Activity.java:2820)
            at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
            at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
            at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
            at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
            at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
            at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Thank you! Great lib!

**Comment by chrisjenx** [comment]
Looks like you are passing in a drawable instead of a font path. Can you
share the XML?

**Comment by thearaks** [comment]
@chrisjenx I'm afraid I can't,
I verified that the menu item causing the warning is the support SearchView.
The XML is from the standard support v7 SearchView layout...

**Comment by chrisjenx** [comment]
Very odd. OK I'll see if I can look into or

**Comment by chrisjenx** [comment]
@thearaks this seems related to #114. I'm going to close this. If you add any information to that issue.

**Comment by chrisjenx** [comment]
The OP issue has been fixed in upcoming 2.0.0.

**Comment by emce** [comment]
I'm using 2.0.2, and it's not crashing the app, but from logcat, I get an error:
`Could not find class 'android.support.v7.widget.Toolbar', referenced from method...`

**Comment by chrisjenx** [comment]
That's normal. It's just looking for the Toolbar. And your not compiling
your app with it.

**Comment by mineshpatel1511** [comment]
@chrisjenx I hear you saying these errors means nothing 
Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.isActionBarSubTitle
Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.isActionBarTitle
Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.parentIsToolbarV7
Could not find class 'android.support.v7.widget.Toolbar', referenced from method uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated 
but whenever I see these errors I see the fonts getting changed in the app. The use case is when the app is opened through a deep link. I am on "com.android.support:support-v4:21.+" and Kitkat 4.4.

**Comment by chrisjenx** [comment]
@mineshpatel1511 correct, you would need the `v7` support library compile in the app. This is normal. See the Calligraphy example .

**Comment by mineshpatel1511** [comment]
@chrisjenx I am wondering why does it need the v7 support only in few cases and not in all cases?

**Comment by chrisjenx** [comment]
You do NOT need the v7 support if you don't use it. The warnings in the logs are normal. It's that I have referenced the classes but ART/Dalvik can't find them. This is normal and safe to ignore. The Library checks if they are provided and won't check if they are not.

**Comment by rraallvv** [comment]
Does anyone know why importing the folder CalligraphySample fails on AndroidStudio?
Should I import the full repository?

**Comment by chrisjenx** [comment]
I think the Sample imports the lib directly intead of maven, you probably need to checkout the whole project.

**Comment by rraallvv** [comment]
@chrisjenx I'll give it a try. Thanks.
