### ISSUE TITLE
Looks like Calligraphy doesn't work on recent Sony devices.

### ISSUE THREAD

**Issue by pepyakin** [chrisjenx/Calligraphy#95]
Affected only these devices Z3 (D6603, D6616, ...), Z3 Compact (D5803, D5833, ...), Z3 Dual (D6633), Z2 (D6503, ...) and Z2 Tablet (SGP521), only with latest firmware update 4.4.4.
I don't have one of these, so I just borrowed one from friend of my friend, so I haven't enough time to investigate further. If someone have such device, please confirm/reject this issue.

Well, there is stacktrace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wheely.wheely/com.wheely.app.ui.home.HomeActivity}: android.view.InflateException: Binary XML file line #41: Error inflating class <unknown>
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2237)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: android.view.InflateException: Binary XML file line #41: Error inflating class <unknown>
       at android.view.LayoutInflater.createView(LayoutInflater.java:620)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:652)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.wheely.app.ui.ServiceBaseActivity$MyLayoutInflater.inflate(ServiceBaseActivity.java:292)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3036)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3099)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1685)
       at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:141)
       at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
       at com.wheely.app.ui.ServiceBaseActivity.onCreate(ServiceBaseActivity.java:123)
       at com.wheely.app.ui.home.HomeActivity.onCreate(HomeActivity.java:115)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:652)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.wheely.app.ui.ServiceBaseActivity$MyLayoutInflater.inflate(ServiceBaseActivity.java:292)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3036)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3099)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1685)
       at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:141)
       at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
       at com.wheely.app.ui.ServiceBaseActivity.onCreate(ServiceBaseActivity.java:123)
       at com.wheely.app.ui.home.HomeActivity.onCreate(HomeActivity.java:115)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at android.content.res.Resources.toPreloadCookie(Resources.java:2185)
       at android.content.res.Resources.loadDrawable(Resources.java:2206)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.ProgressBar.<init>(ProgressBar.java:298)
       at android.widget.ProgressBar.<init>(ProgressBar.java:250)
       at android.widget.ProgressBar.<init>(ProgressBar.java:246)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:652)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
       at com.wheely.app.ui.ServiceBaseActivity$MyLayoutInflater.inflate(ServiceBaseActivity.java:292)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3036)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3099)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1685)
       at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:141)
       at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
       at com.wheely.app.ui.ServiceBaseActivity.onCreate(ServiceBaseActivity.java:123)
       at com.wheely.app.ui.home.HomeActivity.onCreate(HomeActivity.java:115)
       at android.app.Activity.performCreate(Activity.java:5231)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2201)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2286)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.app.ActivityThread.main(ActivityThread.java:5137)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

HomeActivity is ACTION_MAIN/LAUNCHER activity.

Crash occurs when trying to load drawable (looks like it is first on code path) drawable for views inflated for decor view (looks like, it is `android.R.layout.simple_screen`). Crash site is in method `toPreloadCookie`, which I can't find in AOSP. There is also crash in `FrameLayout#<init>` trying to load its `android:foreground` attr drawable instead of `ProgressBar#<init>`. 

When, I removed all the stuff from attachBaseContext (CalligraphyContextWrapper and my context wrapper which just overrides ids in alert_dialog_holo layout for custom layouts in dialogs) it just worked.

```Java    
    private class MyLayoutInflater extends LayoutInflater {
        public MyLayoutInflater(LayoutInflater original, Context newContext) {
            super(original, newContext);
        }

        @Override
        public LayoutInflater cloneInContext(Context newContext) {
            return new MyLayoutInflater(this, newContext);
        }

        @Override
        public View inflate(int resource, ViewGroup root, boolean attachToRoot) {
            if (resource == R.layout.alert_dialog_holo) {
                View v = super.inflate(R.layout.alert_dialog_holo, root, attachToRoot);
                setSystemIds(v);
                return v;
            } else {
                return super.inflate(resource, root, attachToRoot);
            }
        }

        private void setSystemIds(View view) {
            final int id = view.getId();
            if (id != View.NO_ID) {
                Resources r = getResources();
                final String resourceEntryName = r.getResourceEntryName(id);

                final int identifier = Resources.getSystem()
                        .getIdentifier(resourceEntryName, "id", "android");
                view.setId(identifier);
            }

            if (view instanceof ViewGroup) {
                ViewGroup vg = (ViewGroup) view;
                final int childCount = vg.getChildCount();
                for (int i = 0; i < childCount; i++) {
                    final View childAt = vg.getChildAt(i);
                    setSystemIds(childAt);
                }
            }
        }
    }
```

I don't think the problem is in my layout inflater, because I had no chance to start dialog there (Just because `super.onCreate(savedInstanceState)` is first thing I call in onCreate).

**Comment by chrisjenx** [comment]
This should all be fixed in 2.x. Closing, let me know if still an issue.

**Comment by xmenxwk** [comment]
Could you please explain, how did you fix it ?
