### ISSUE TITLE
ViewStub

### ISSUE THREAD

**Issue by illarionov** [chrisjenx/Calligraphy#97]
Calligraphy does not change font in the layout that is inflated by ViewStub.

CalligraphySample with ViewStub:

https://github.com/illarionov/Calligraphy/commit/eed3f9eaefb10500c57b4ee3c6af09c5b9bb894b

![screenshot2](https://cloud.githubusercontent.com/assets/482800/5199832/d783eca0-7570-11e4-8333-dc27f90d43bc.png)

**Comment by chrisjenx** [comment]
@orrc this is working for me in the 2.0.0-SNAPSHOT

**Comment by orrc** [comment]
Yeah, seems to work in the latest snapshot on maven central, thanks.

**Comment by chrisjenx** [comment]
Nuice thanks! :D

**Comment by n-belokopytov** [comment]
Now I just had a crash
  android.view.InflateException: Binary XML file line #65: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:162)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
while inflating a view. 65th line is a viewstub
                <ViewStub
                    android:id="@+id/stub_nearby_dishes_1"
                    android:inflatedId="@+id/nearby_dishes_1"
                    android:layout="@layout/dish_preview"
                    android:layout_width="0dp"
                    android:layout_weight="0.5"
                    android:layout_marginRight="6dp"
                    android:layout_marginLeft="6dp"
                    android:layout_height="@dimen/home_card_height" />

**Comment by chrisjenx** [comment]
Your inner view you are creating has a broken constructor

**Comment by n-belokopytov** [comment]
I don't have a constuctor. It's a default ViewStub

**Comment by chrisjenx** [comment]
@n-belokopytov 1. check you are using 2.1.+ and 2 check that this actually works with Calligraphy disabled. There is nothing in that stacktrace that points to Calligraphy, those kind of issues are related to a broken view.

**Comment by n-belokopytov** [comment]
Works on Calligraphy 2.1.0, thanks!
